<a href="https://colab.research.google.com/github/PriyankaDevaprasad/Projects/blob/main/Project_1__Cross_market_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
!pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)

**Extracting 5 pages of crytocurrency data**

In [8]:
all_records = []
import requests

for i in range(1,6):
  url = f"https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&per_page=250&order=market_cap_desc&page={i}&sparkline=False"
  response = requests.get(url)
  print(response)
  if response.status_code == 200:
    data = response.json()
    all_records.extend(data)

<Response [200]>
<Response [200]>
<Response [200]>
<Response [429]>
<Response [429]>

In [9]:
all_records

[{'id': 'bitcoin',
  'symbol': 'btc',
  'name': 'Bitcoin',
  'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
  'current_price': 70412,
  'market_cap': 1407570518748,
  'market_cap_rank': 1,
  'fully_diluted_valuation': 1407570518748,
  'total_volume': 40857128560,
  'high_24h': 71261,
  'low_24h': 68934,
  'price_change_24h': 1256.9,
  'price_change_percentage_24h': 1.81751,
  'market_cap_change_24h': 19962945915,
  'market_cap_change_percentage_24h': 1.43866,
  'circulating_supply': 20003043.0,
  'total_supply': 20003043.0,
  'max_supply': 21000000.0,
  'ath': 126080,
  'ath_change_percentage': -44.15287,
  'ath_date': '2025-10-06T18:57:42.558Z',
  'atl': 67.81,
  'atl_change_percentage': 103738.71962,
  'atl_date': '2013-07-06T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-20T13:10:00.513Z'},
 {'id': 'ethereum',
  'symbol': 'eth',
  'name': 'Ethereum',
  'image': 'https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628',
  'current_price': 2143.51,
  'market_cap': 258400050398,
  'market_cap_rank': 2,
  'fully_diluted_valuation': 258400050398,
  'total_volume': 21204807932,
  'high_24h': 2170.04,
  'low_24h': 2104.6,
  'price_change_24h': 22.65,
  'price_change_percentage_24h': 1.06787,
  'market_cap_change_24h': 1154924284,
  'market_cap_change_percentage_24h': 0.44896,
  'circulating_supply': 120691772.3575402,
  'total_supply': 120691772.3575402,
  'max_supply': None,
  'ath': 4946.05,
  'ath_change_percentage': -56.66218,
  'ath_date': '2025-08-24T19:21:03.333Z',
  'atl': 0.432979,
  'atl_change_percentage': 494961.02736,
  'atl_date': '2015-10-20T00:00:00.000Z',
  'roi': {'times': 39.69650082074312,
   'currency': 'btc',
   'percentage': 3969.650082074312},
  'last_updated': '2026-03-20T13:10:00.748Z'},
 {'id': 'tether',
  'symbol': 'usdt',
  'name': 'Tether',
  'image': 'https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661',
  'current_price': 0.999822,
  'market_cap': 184152928583,
  'market_cap_rank': 3,
  'fully_diluted_valuation': 189618966282,
  'total_volume': 68123889445,
  'high_24h': 1.0,
  'low_24h': 0.999827,
  'price_change_24h': -9.6604022202462e-05,
  'price_change_percentage_24h': -0.00966,
  'market_cap_change_24h': 71848261,
  'market_cap_change_percentage_24h': 0.03903,
  'circulating_supply': 184183287831.1904,
  'total_supply': 189650226655.5562,
  'max_supply': None,
  'ath': 1.32,
  'ath_change_percentage': -24.43273,
  'ath_date': '2018-07-24T00:00:00.000Z',
  'atl': 0.572521,
  'atl_change_percentage': 74.63587,
  'atl_date': '2015-03-02T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-20T13:09:51.424Z'},
 {'id': 'ripple',
  'symbol': 'xrp',
  'name': 'XRP',
  'image': 'https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442',
  'current_price': 1.44,
  'market_cap': 88426626554,
  'market_cap_rank': 4,
  'fully_diluted_valuation': 144277091788,
  'total_volume': 2222850241,
  'high_24h': 1.46,
  'low_24h': 1.42,
  'price_change_24h': 0.00401719,
  'price_change_percentage_24h': 0.27913,
  'market_cap_change_24h': 381361613,
  'market_cap_change_percentage_24h': 0.43314,
  'circulating_supply': 61280678111.0,
  'total_supply': 99985698485.0,
  'max_supply': 100000000000.0,
  'ath': 3.65,
  'ath_change_percentage': -60.42112,
  'ath_date': '2025-07-18T03:40:53.808Z',
  'atl': 0.00268621,
  'atl_change_percentage': 53626.16122,
  'atl_date': '2014-05-22T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-20T13:09:51.309Z'},
 {'id': 'binancecoin',
  'symbol': 'bnb',
  'name': 'BNB',
  'image': 'https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970',
  'current_price': 642.02,
  'market_cap': 87508307359,
  'market_cap_rank': 5,
  'fully_diluted_valuation': 87508307359,
  'total_volume': 1011651503,
  'high_24h': 646.71,
  'low_24h': 633.79,
  'price_change_24h': 4.52,
  'price_change_percentage_24h': 0.70954,
  'market_cap_change_24h': 379629920,
  'market_cap_change_percentage_24h': 0.43571,
  'circulating_supply': 136357690.23,
  'total_supply': 136357690.23,
  'max_supply': 200000000.0,
  'ath': 1369.99,
  'ath_change_percentage': -53.13703,
  'ath_date': '2025-10-13T08:41:24.131Z',
  'atl': 0.0398177,
  'atl_change_percentage': 1612295.49578,
  'atl_date': '2017-10-19T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-20T13:10:01.132Z'},
 {'id': 'usd-coin',
  'symbol': 'usdc',
  'name': 'USDC',
  'image': 'https://coin-images.coingecko.com/coins/images/6319/large/USDC.png?1769615602',
  'current_price': 0.999993,
  'market_cap': 79200146079,
  'market_cap_rank': 6,
  'fully_diluted_valuation': 79202853934,
  'total_volume': 5019215520,
  'high_24h': 1.0,
  'low_24h': 0.999812,
  'price_change_24h': 4.56e-06,
  'price_change_percentage_24h': 0.00046,
  'market_cap_change_24h': -250009146.40896606,
  'market_cap_change_percentage_24h': -0.31467,
  'circulating_supply': 79204826267.13542,
  'total_supply': 79207534281.53183,
  'max_supply': None,
  'ath': 1.043,
  'ath_change_percentage': -4.17868,
  'ath_date': '2018-11-15T00:00:00.000Z',
  'atl': 0.877647,
  'atl_change_percentage': 13.9253,
  'atl_date': '2023-03-11T08:02:13.981Z',
  'roi': None,
  'last_updated': '2026-03-20T13:09:51.420Z'},
 {'id': 'solana',
  'symbol': 'sol',
  'name': 'Solana',
  'image': 'https://coin-images.coingecko.com/coins/images/4128/large/solana.png?1718769756',
  'current_price': 89.35,
  'market_cap': 51012818819,
  'market_cap_rank': 7,
  'fully_diluted_valuation': 51012820416,
  'total_volume': 3309403748,
  'high_24h': 90.13,
  'low_24h': 87.28,
  'price_change_24h': 1.18,
  'price_change_percentage_24h': 1.33954,
  'market_cap_change_24h': 628520293,
  'market_cap_change_percentage_24h': 1.24745,
  'circulating_supply': 571566834.6584237,
  'total_supply': 571566852.5563036,
  'max_supply': None,
  'ath': 293.31,
  'ath_change_percentage': -69.53865,
  'ath_date': '2025-01-19T11:15:27.957Z',
  'atl': 0.500801,
  'atl_change_percentage': 17740.76757,
  'atl_date': '2020-05-11T19:35:23.449Z',
  'roi': None,
  'last_updated': '2026-03-20T13:09:51.346Z'},
 {'id': 'tron',
  'symbol': 'trx',
  'name': 'TRON',
  'image': 'https://coin-images.coingecko.com/coins/images/1094/large/tron-logo.png?1696502193',
  'current_price': 0.305928,
  'market_cap': 28982787479,
  'market_cap_rank': 8,
  'fully_diluted_valuation': 28982792106,
  'total_volume': 555377801,
  'high_24h': 0.307462,
  'low_24h': 0.299405,
  'price_change_24h': 0.0040513,
  'price_change_percentage_24h': 1.34204,
  'market_cap_change_24h': 376492451,
  'market_cap_change_percentage_24h': 1.31612,
  'circulating_supply': 94751919082.7549,
  'total_supply': 94751934207.1034,
  'max_supply': None,
  'ath': 0.431288,
  'ath_change_percentage': -29.06653,
  'ath_date': '2024-12-04T00:10:40.323Z',
  'atl': 0.00180434,
  'atl_change_percentage': 16855.09375,
  'atl_date': '2017-11-12T00:00:00.000Z',
  'roi': {'times': 160.01463983680557,
   'currency': 'usd',
   'percentage': 16001.463983680558},
  'last_updated': '2026-03-20T13:09:51.101Z'},
 {'id': 'figure-heloc',
  'symbol': 'figr_heloc',
  'name': 'Figure Heloc',
  'image': 'https://coin-images.coingecko.com/coins/images/68480/large/figure.png?1755863954',
  'current_price': 1.002,
  'market_cap': 15870605852,
  'market_cap_rank': 9,
  'fully_diluted_valuation': 15870605852,
  'total_volume': 330527457,
  'high_24h': 1.033,
  'low_24h': 1.002,
  'price_change_24h': -0.0231939000000001,
  'price_change_percentage_24h': -2.26304,
  'market_cap_change_24h': -367473526.7839794,
  'market_cap_change_percentage_24h': -2.26304,
  'circulating_supply': 15843541913.347,
  'total_supply': 15843541913.347,
  'max_supply': None,
  'ath': 1.049,
  'ath_change_percentage': -4.51907,
  'ath_date': '2026-03-09T17:00:25.937Z',
  'atl': 0.155357,
  'atl_change_percentage': 544.77994,
  'atl_date': '2025-10-31T14:27:24.456Z',
  'roi': None,
  'last_updated': '2026-03-20T13:09:50.833Z'},
 {'id': 'dogecoin',
  'symbol': 'doge',
  'name': 'Dogecoin',
  'image': 'https://coin-images.coingecko.com/coins/images/5/large/dogecoin.png?1696501409',
  'current_price': 0.093972,
  'market_cap': 14413096021,
  'market_cap_rank': 10,
  'fully_diluted_valuation': 15888496562,
  'total_volume': 807322420,
  'high_24h': 0.095178,
  'low_24h': 0.091933,
  'price_change_24h': 0.0013885,
  'price_change_percentage_24h': 1.49973,
  'market_cap_change_24h': 203613902,
  'market_cap_change_percentage_24h': 1.43294,
  'circulating_supply': 153487466383.7052,
  'total_supply': 169199253126.5791,
  'max_supply': None,
  'ath': 0.731578,
  'ath_change_percentage': -87.15496,
  'ath_date': '2021-05-08T05:08:23.458Z',
  'atl': 8.69e-05,
  'atl_change_percentage': 108032.87992,
  'atl_date': '2015-05-06T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-20T13:09:51.141Z'},
 {'id': 'whitebit',
  'symbol': 'wbt',
  'name': 'WhiteBIT Coin',
  'image': 'https://coin-images.coingecko.com/coins/images/27045/large/wbt_token.png?1696526096',
  'current_price': 55.14,
  'market_cap': 11766111135,
  'market_cap_rank': 11,
  'fully_diluted_valuation': 17637636626,
  'total_volume': 70683416,
  'high_24h': 55.84,
  'low_24h': 54.65,
  'price_change_24h': -0.031395448995525044,
  'price_change_percentage_24h': -0.05691,
  'market_cap_change_24h': -8937579.216186523,
  'market_cap_change_percentage_24h': -0.0759,
  'circulating_supply': 213418274.0,
  'total_supply': 319918274.0,
  'max_supply': 400000000.0,
  'ath': 64.11,
  'ath_change_percentage': -14.01061,
  'ath_date': '2025-12-10T20:16:13.582Z',
  'atl': 3.06,
  'atl_change_percentage': 1700.44579,
  'atl_date': '2023-02-13T19:01:21.899Z',
  'roi': None,
  'last_updated': '2026-03-20T13:09:50.863Z'},
 {'id': 'usds',
  'symbol': 'usds',
  'name': 'USDS',
  'image': 'https://coin-images.coingecko.com/coins/images/39926/large/usds.webp?1726666683',
  'current_price': 0.999855,
  'market_cap': 11499134711,
  'market_cap_rank': 12,
  'fully_diluted_valuation': 11499134711,
  'total_volume': 7334107,
  'high_24h': 1.001,
  'low_24h': 0.995309,
  'price_change_24h': 0.00030653,
  'price_change_percentage_24h': 0.03067,
  'market_cap_change_24h': -73296769.59511566,
  'market_cap_change_percentage_24h': -0.63337,
  'circulating_supply': 11500786540.22164,
  'total_supply': 11500786540.22164,
  'max_supply': None,
  'ath': 1.057,
  'ath_change_percentage': -5.42935,
  'ath_date': '2024-10-29T05:40:51.197Z',
  'atl': 0.948265,
  'atl_change_percentage': 5.44693,
  'atl_date': '2024-10-03T13:19:28.826Z',
  'roi': None,
  'last_updated': '2026-03-20T13:09:53.045Z'},
 {'id': 'cardano',
  'symbol': 'ada',
  'name': 'Cardano',
  'image': 'https://coin-images.coingecko.com/coins/images/975/large/cardano.png?1696502090',
  'current_price': 0.267602,
  'market_cap': 9854399006,
  'market_cap_rank': 13,
  'fully_diluted_valuation': 12034863112,
  'total_volume': 387125671,
  'high_24h': 0.272712,
  'low_24h': 0.263103,
  'price_change_24h': 0.00264652,
  'price_change_percentage_24h': 0.99885,
  'market_cap_change_24h': 91748029,
  'market_cap_change_percentage_24h': 0.93979,
  'circulating_supply': 36846946339.91323,
  'total_supply': 45000000000.0,
  'max_supply': 45000000000.0,
  'ath': 3.09,
  'ath_change_percentage': -91.33107,
  'ath_date': '2021-09-02T06:00:10.474Z',
  'atl': 0.01925275,
  'atl_change_percentage': 1289.94346,
  'atl_date': '2020-03-13T02:22:55.044Z',
  'roi': None,
  'last_updated': '2026-03-20T13:09:51.414Z'},
 {'id': 'hyperliquid',
  'symbol': 'hype',
  'name': 'Hyperliquid',
  'image': 'https://coin-images.coingecko.com/coins/images/50882/large/hyperliquid.jpg?1729431300',
  'current_price': 39.55,
  'market_cap': 9429530910,
  'market_cap_rank': 14,
  'fully_diluted_valuation': 38063555484,
  'total_volume': 353067575,
  'high_24h': 40.54,
  'low_24h': 38.77,
  'price_change_24h': 0.534696,
  'price_change_percentage_24h': 1.37053,
  'market_cap_change_24h': 151872732,
  'market_cap_change_percentage_24h': 1.63697,
  'circulating_supply': 238385315.9541414,
  'total_supply': 962274028.9541414,
  'max_supply': 1000000000.0,
  'ath': 59.3,
  'ath_change_percentage': -33.31184,
  'ath_date': '2025-09-18T03:30:30.650Z',
  'atl': 3.81,
  'atl_change_percentage': 938.36219,
  'atl_date': '2024-11-29T09:30:30.871Z',
  'roi': None,
  'last_updated': '2026-03-20T13:09:51.111Z'},
 {'id': 'bitcoin-cash',
  'symbol': 'bch',
  'name': 'Bitcoin Cash',
  'image': 'https://coin-images.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png?1696501932',
  'current_price': 467.46,
  'market_cap': 9351016876,
  'market_cap_rank': 15,
  'fully_diluted_valuation': 9351021257,
  'total_volume': 205877367,
  'high_24h': 470.2,
  'low_24h': 452.32,
  'price_change_24h': 13.73,
  'price_change_percentage_24h': 3.02634,
  'market_cap_change_24h': 277249464,
  'market_cap_change_percentage_24h': 3.05551,
  'circulating_supply': 20009899.89665078,
  'total_supply': 20009909.27165078,
  'max_supply': 21000000.0,
  'ath': 3785.82,
  'ath_change_percentage': -87.65228,
  'ath_date': '2017-12-20T00:00:00.000Z',
  'atl': 76.93,
  'atl_change_percentage': 507.60839,
  'atl_date': '2018-12-16T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-20T13:09:51.119Z'},
 {'id': 'leo-token',
  'symbol': 'leo',
  'name': 'LEO Token',
  'image': 'https://coin-images.coingecko.com/coins/images/8418/large/leo-token.png?1696508607',
  'current_price': 9.2,
  'market_cap': 8477054755,
  'market_cap_rank': 16,
  'fully_diluted_valuation': 9067666067,
  'total_volume': 820785,
  'high_24h': 9.23,
  'low_24h': 9.16,
  'price_change_24h': 0.03853602,
  'price_change_percentage_24h': 0.42047,
  'market_cap_change_24h': 44426096,
  'market_cap_change_percentage_24h': 0.52684,
  'circulating_supply': 921067136.9,
  'total_supply': 985239504.0,
  'max_supply': None,
  'ath': 10.14,
  'ath_change_percentage': -9.39752,
  'ath_date': '2025-03-10T09:26:43.294Z',
  'atl': 0.799859,
  'atl_change_percentage': 1048.03465,
  'atl_date': '2019-12-24T15:14:35.376Z',
  'roi': None,
  'last_updated': '2026-03-20T13:09:50.902Z'},
 {'id': 'monero',
  'symbol': 'xmr',
  'name': 'Monero',
  'image': 'https://coin-images.coingecko.com/coins/images/69/large/monero_logo.png?1696501460',
  'current_price': 349.07,
  'market_cap': 6429303123,
  'market_cap_rank': 17,
  'fully_diluted_valuation': 6429303123,
  'total_volume': 83785235,
  'high_24h': 348.55,
  'low_24h': 336.6,
  'price_change_24h': 6.92,
  'price_change_percentage_24h': 2.02391,
  'market_cap_change_24h': 116679946,
  'market_cap_change_percentage_24h': 1.84836,
  'circulating_supply': 18446744.07370955,
  'total_supply': 18446744.07370955,
  'max_supply': None,
  'ath': 797.73,
  'ath_change_percentage': -56.24265,
  'ath_date': '2026-01-14T19:34:07.049Z',
  'atl': 0.216177,
  'atl_change_percentage': 161373.29585,
  'atl_date': '2015-01-14T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-20T13:09:50.975Z'},
 {'id': 'chainlink',
  'symbol': 'link',
  'name': 'Chainlink',
  'image': 'https://coin-images.coingecko.com/coins/images/877/large/Chainlink_Logo_500.png?1760023405',
  'current_price': 9.08,
  'market_cap': 6428704047,
  'market_cap_rank': 18,
  'fully_diluted_valuation': 9078808523,
  'total_volume': 357053834,
  'high_24h': 9.18,
  'low_24h': 8.91,
  'price_change_24h': 0.12167,
  'price_change_percentage_24h': 1.35778,
  'market_cap_change_24h': 84017163,
  'market_cap_change_percentage_24h': 1.32421,
  'circulating_supply': 708099970.4525867,
  'total_supply': 1000000000.0,
  'max_supply': 1000000000.0,
  'ath': 52.7,
  'ath_change_percentage': -82.76428,
  'ath_date': '2021-05-10T00:13:57.214Z',
  'atl': 0.148183,
  'atl_change_percentage': 6029.33029,
  'atl_date': '2017-11-29T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-20T13:09:51.300Z'},
 {'id': 'ethena-usde',
  'symbol': 'usde',
  'name': 'Ethena USDe',
  'image': 'https://coin-images.coingecko.com/coins/images/33613/large/usde.png?1733810059',
  'current_price': 1.0,
  'market_cap': 5924913582,
  'market_cap_rank': 19,
  'fully_diluted_valuation': 5924913582,
  'total_volume': 100997245,
  'high_24h': 1.001,
  'low_24h': 0.999207,
  'price_change_24h': 0.00058139,
  'price_change_percentage_24h': 0.05817,
  'market_cap_change_24h': 5169303,
  'market_cap_change_percentage_24h': 0.08732,
  'circulating_supply': 5924976969.764292,
  'total_supply': 5924976969.764292,
  'max_supply': None,
  'ath': 1.034,
  'ath_change_percentage': -3.29182,
  'ath_date': '2025-12-09T17:10:12.652Z',
  'atl': 0.929486,
  'atl_change_percentage': 7.58479,
  'atl_date': '2024-10-04T07:57:15.809Z',
  'roi': None,
  'last_updated': '2026-03-20T13:09:51.057Z'},
 {'id': 'stellar',
  'symbol': 'xlm',
  'name': 'Stellar',
  'image': 'https://coin-images.coingecko.com/coins/images/100/large/fmpFRHHQ_400x400.jpg?1735231350',
  'current_price': 0.167076,
  'market_cap': 5514292158,
  'market_cap_rank': 20,
  'fully_diluted_valuation': 8352707385,
  'total_volume': 81597107,
  'high_24h': 0.168439,
  'low_24h': 0.163664,
  'price_change_24h': 0.00194422,
  'price_change_percentage_24h': 1.17737,
  'market_cap_change_24h': 64168418,
  'market_cap_change_percentage_24h': 1.17738,
  'circulating_supply': 33010190420.54276,
  'total_supply': 50001786883.65895,
  'max_supply': None,
  'ath': 0.875563,
  'ath_change_percentage': -80.92907,
  'ath_date': '2018-01-03T00:00:00.000Z',
  'atl': 0.00047612,
  'atl_change_percentage': 34970.32036,
  'atl_date': '2015-03-05T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-20T13:09:51.440Z'},
 {'id': 'canton-network',
  'symbol': 'cc',
  'name': 'Canton',
  'image': 'https://coin-images.coingecko.com/coins/images/70468/large/Canton-Ticker_%281%29.png?1762826299',
  'current_price': 0.142518,
  'market_cap': 5430288719,
  'market_cap_rank': 21,
  'fully_diluted_valuation': 5430288719,
  'total_volume': 6838131,
  'high_24h': 0.146147,
  'low_24h': 0.142175,
  'price_change_24h': -0.003017952348644742,
  'price_change_percentage_24h': -2.07368,
  'market_cap_change_24h': -109982123.58966732,
  'market_cap_change_percentage_24h': -1.98514,
  'circulating_supply': 38078720256.30869,
  'total_supply': 38078720256.30869,
  'max_supply': None,
  'ath': 0.194152,
  'ath_change_percentage': -26.53313,
  'ath_date': '2026-02-03T08:02:08.411Z',
  'atl': 0.059024,
  'atl_change_percentage': 141.65934,
  'atl_date': '2025-12-06T10:32:09.784Z',
  'roi': None,
  'last_updated': '2026-03-20T13:09:50.952Z'},
 {'id': 'usd1-wlfi',
  'symbol': 'usd1',
  'name': 'USD1',
  'image': 'https://coin-images.coingecko.com/coins/images/54977/large/USD1_1000x1000_transparent.png?1749297002',
  'current_price': 0.999275,
  'market_cap': 4439467647,
  'market_cap_rank': 22,
  'fully_diluted_valuation': 4439467647,
  'total_volume': 2225262559,
  'high_24h': 0.999766,
  'low_24h': 0.998579,
  'price_change_24h': 0.00049979,
  'price_change_percentage_24h': 0.05004,
  'market_cap_change_24h': -53442031.87383461,
  'market_cap_change_percentage_24h': -1.18947,
  'circulating_supply': 4442689588.325259,
  'total_supply': 4442689588.325259,
  'max_supply': None,
  'ath': 1.025,
  'ath_change_percentage': -2.48738,
  'ath_date': '2025-05-12T12:36:39.412Z',
  'atl': 0.989633,
  'atl_change_percentage': 0.98036,
  'atl_date': '2025-10-01T08:51:32.103Z',
  'roi': None,
  'last_updated': '2026-03-20T13:09:52.172Z'},
 {'id': 'dai',
  'symbol': 'dai',
  'name': 'Dai',
  'image': 'https://coin-images.coingecko.com/coins/images/9956/large/Badge_Dai.png?1696509996',
  'current_price': 0.999882,
  'market_cap': 4322726775,
  'market_cap_rank': 23,
  'fully_diluted_valuation': 4322726775,
  'total_volume': 150126039,
  'high_24h': 1.0,
  'low_24h': 0.99901,
  'price_change_24h': -8.4603985828657e-05,
  'price_change_percentage_24h': -0.00846,
  'market_cap_change_24h': 17612649,
  'market_cap_change_percentage_24h': 0.40911,

In [10]:
len(all_records)

750

**converting the data into dataframe**

In [11]:
import pandas as pd
crypto = pd.DataFrame(all_records)
crypto

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,70412.000000,1407570518748,1,1.407571e+12,4.085713e+10,71261.000000,...,2.000304e+07,2.100000e+07,126080.000000,-44.15287,2025-10-06T18:57:42.558Z,67.810000,1.037387e+05,2013-07-06T00:00:00.000Z,None,2026-03-20T13:10:00.513Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,2143.510000,258400050398,2,2.584001e+11,2.120481e+10,2170.040000,...,1.206918e+08,NaN,4946.050000,-56.66218,2025-08-24T19:21:03.333Z,0.432979,4.949610e+05,2015-10-20T00:00:00.000Z,"{'times': 39.69650082074312, 'currency': 'btc'...",2026-03-20T13:10:00.748Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.999822,184152928583,3,1.896190e+11,6.812389e+10,1.000000,...,1.896502e+11,NaN,1.320000,-24.43273,2018-07-24T00:00:00.000Z,0.572521,7.463587e+01,2015-03-02T00:00:00.000Z,None,2026-03-20T13:09:51.424Z
3,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,1.440000,88426626554,4,1.442771e+11,2.222850e+09,1.460000,...,9.998570e+10,1.000000e+11,3.650000,-60.42112,2025-07-18T03:40:53.808Z,0.002686,5.362616e+04,2014-05-22T00:00:00.000Z,None,2026-03-20T13:09:51.309Z
4,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,642.020000,87508307359,5,8.750831e+10,1.011652e+09,646.710000,...,1.363577e+08,2.000000e+08,1369.990000,-53.13703,2025-10-13T08:41:24.131Z,0.039818,1.612295e+06,2017-10-19T00:00:00.000Z,None,2026-03-20T13:10:01.132Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
745,honey-3,honey,Honey,https://coin-images.coingecko.com/coins/images...,0.999249,24201102,746,2.420111e+07,4.456920e+05,1.003000,...,2.421903e+07,NaN,2.000000,-49.99490,2026-02-20T11:36:47.384Z,0.916153,9.070380e+00,2025-02-06T14:06:00.806Z,None,2026-03-20T13:10:03.043Z
746,bifrost,bfc,Bifrost,https://coin-images.coingecko.com/coins/images...,0.017359,24150726,747,4.111569e+07,6.974810e+05,0.018154,...,2.368584e+09,NaN,0.778815,-97.77030,2021-08-19T00:15:06.996Z,0.014953,1.613350e+01,2026-02-05T22:55:13.675Z,None,2026-03-20T13:10:03.015Z
747,singularitynet,agix,SingularityNET,https://coin-images.coingecko.com/coins/images...,0.097941,24141951,748,4.349297e+07,5.484600e+04,0.103186,...,4.442360e+08,2.000000e+09,1.460000,-93.30474,2024-03-10T00:24:59.207Z,0.007472,1.209052e+03,2020-03-13T02:24:16.528Z,"{'times': -0.0205887681374482, 'currency': 'us...",2026-03-20T13:10:03.003Z
748,infinex-2,inx,Infinex,https://coin-images.coingecko.com/coins/images...,0.012084,24097212,749,1.208304e+08,1.841635e+06,0.012345,...,1.000000e+10,1.000000e+10,0.033392,-63.83366,2026-01-30T19:03:44.411Z,0.010668,1.320625e+01,2026-02-23T20:06:38.137Z,None,2026-03-20T13:10:03.022Z
749,caldera,era,Caldera,https://coin-images.coingecko.com/coins/images...,0.137589,24044073,750,1.375913e+08,3.402490e+06,0.138050,...,1.000000e+09,1.000000e+09,1.880000,-92.67510,2025-07-17T20:36:33.109Z,0.130308,5.452220e+00,2026-02-06T00:25:08.873Z,None,2026-03-20T13:10:03.081Z

**Filtering only the required columns**

In [12]:
crypto_filter=crypto[['id', 'symbol', 'name', 'current_price', 'market_cap', 'market_cap_rank', 'total_volume', 'circulating_supply', 'total_supply', 'ath', 'atl', 'last_updated']]

In [13]:
crypto_filter

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,70412.000000,1407570518748,1,4.085713e+10,2.000304e+07,2.000304e+07,126080.000000,67.810000,2026-03-20T13:10:00.513Z
1,ethereum,eth,Ethereum,2143.510000,258400050398,2,2.120481e+10,1.206918e+08,1.206918e+08,4946.050000,0.432979,2026-03-20T13:10:00.748Z
2,tether,usdt,Tether,0.999822,184152928583,3,6.812389e+10,1.841833e+11,1.896502e+11,1.320000,0.572521,2026-03-20T13:09:51.424Z
3,ripple,xrp,XRP,1.440000,88426626554,4,2.222850e+09,6.128068e+10,9.998570e+10,3.650000,0.002686,2026-03-20T13:09:51.309Z
4,binancecoin,bnb,BNB,642.020000,87508307359,5,1.011652e+09,1.363577e+08,1.363577e+08,1369.990000,0.039818,2026-03-20T13:10:01.132Z
...,...,...,...,...,...,...,...,...,...,...,...,...
745,honey-3,honey,Honey,0.999249,24201102,746,4.456920e+05,2.421902e+07,2.421903e+07,2.000000,0.916153,2026-03-20T13:10:03.043Z
746,bifrost,bfc,Bifrost,0.017359,24150726,747,6.974810e+05,1.391270e+09,2.368584e+09,0.778815,0.014953,2026-03-20T13:10:03.015Z
747,singularitynet,agix,SingularityNET,0.097941,24141951,748,5.484600e+04,2.465852e+08,4.442360e+08,1.460000,0.007472,2026-03-20T13:10:03.003Z
748,infinex-2,inx,Infinex,0.012084,24097212,749,1.841635e+06,1.994300e+09,1.000000e+10,0.033392,0.010668,2026-03-20T13:10:03.022Z
749,caldera,era,Caldera,0.137589,24044073,750,3.402490e+06,1.747500e+08,1.000000e+09,1.880000,0.130308,2026-03-20T13:10:03.081Z

In [14]:
crypto_filter.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750 entries, 0 to 749
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  750 non-null    object
 1   symbol              750 non-null    object
 2   name                750 non-null    object
 3   current_price       750 non-null    float64
 4   market_cap          750 non-null    int64
 5   market_cap_rank     750 non-null    int64
 6   total_volume        750 non-null    float64
 7   circulating_supply  750 non-null    float64
 8   total_supply        749 non-null    float64
 9   ath                 750 non-null    float64
 10  atl                 750 non-null    float64
 11  last_updated        750 non-null    object
dtypes: float64(6), int64(2), object(4)
memory usage: 70.4+ KB

In [15]:
crypto_filter['last_updated'] = pd.to_datetime(crypto_filter['last_updated'])
crypto_filter['last_updated'] = crypto_filter['last_updated'].dt.date
crypto_filter

/tmp/ipykernel_1156/2515190835.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crypto_filter['last_updated'] = pd.to_datetime(crypto_filter['last_updated'])
/tmp/ipykernel_1156/2515190835.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crypto_filter['last_updated'] = crypto_filter['last_updated'].dt.date

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,70412.000000,1407570518748,1,4.085713e+10,2.000304e+07,2.000304e+07,126080.000000,67.810000,2026-03-20
1,ethereum,eth,Ethereum,2143.510000,258400050398,2,2.120481e+10,1.206918e+08,1.206918e+08,4946.050000,0.432979,2026-03-20
2,tether,usdt,Tether,0.999822,184152928583,3,6.812389e+10,1.841833e+11,1.896502e+11,1.320000,0.572521,2026-03-20
3,ripple,xrp,XRP,1.440000,88426626554,4,2.222850e+09,6.128068e+10,9.998570e+10,3.650000,0.002686,2026-03-20
4,binancecoin,bnb,BNB,642.020000,87508307359,5,1.011652e+09,1.363577e+08,1.363577e+08,1369.990000,0.039818,2026-03-20
...,...,...,...,...,...,...,...,...,...,...,...,...
745,honey-3,honey,Honey,0.999249,24201102,746,4.456920e+05,2.421902e+07,2.421903e+07,2.000000,0.916153,2026-03-20
746,bifrost,bfc,Bifrost,0.017359,24150726,747,6.974810e+05,1.391270e+09,2.368584e+09,0.778815,0.014953,2026-03-20
747,singularitynet,agix,SingularityNET,0.097941,24141951,748,5.484600e+04,2.465852e+08,4.442360e+08,1.460000,0.007472,2026-03-20
748,infinex-2,inx,Infinex,0.012084,24097212,749,1.841635e+06,1.994300e+09,1.000000e+10,0.033392,0.010668,2026-03-20
749,caldera,era,Caldera,0.137589,24044073,750,3.402490e+06,1.747500e+08,1.000000e+09,1.880000,0.130308,2026-03-20

In [16]:
crypto_filter.to_csv("crypto.csv",index=False)

**Extracting the date and price of top 3 cryptocurrency**

In [17]:
coin_id = ["bitcoin","ethereum","tether"]
coins_hist=[]
for i in coin_id:
  url = f"https://api.coingecko.com/api/v3/coins/{i}/market_chart?vs_currency=usd&days=365"
  response = requests.get(url)
  if response.status_code == 200:
    hist_price=response.json() # pandas dateime and convert this milliseconds and extract only the date
    print(hist_price)
    hist_price=hist_price['prices']
    for j,k in hist_price:
      coins_hist.append({"coin_id":i, "date": pd.to_datetime(j, unit="ms"),"price_usd": k})
print(coins_hist)

{'prices': [[1742515200000, 84270.84358966233], [1742601600000, 84009.532917822], [1742688000000, 83793.30854192551], [1742774400000, 85787.70914901773], [1742860800000, 87327.72969669085], [1742947200000, 87520.58391530563], [1743033600000, 86960.8555491039], [1743120000000, 87227.27158032371], [1743206400000, 84359.46915506005], [1743292800000, 82679.17255385047], [1743379200000, 82356.38111183756], [1743465600000, 82514.09365397849], [1743552000000, 85237.5876052852], [1743638400000, 82526.4221526433], [1743724800000, 83163.98757387721], [1743811200000, 83852.00765399594], [1743897600000, 83595.88550177493], [1743984000000, 78211.48358199988], [1744070400000, 79179.29226757778], [1744156800000, 76329.090356324], [1744243200000, 82622.17029546302], [1744329600000, 79596.35732250768], [1744416000000, 83439.28818043756], [1744502400000, 85305.09728392666], [1744588800000, 83600.82010054543], [1744675200000, 84523.4524914945], [1744761600000, 83656.49248858042], [1744848000000, 84105.77942167096], [1744934400000, 84930.90857600998], [1745020800000, 84433.75017215389], [1745107200000, 85126.66244301842], [1745193600000, 85073.16544858096], [1745280000000, 87452.04699068287], [1745366400000, 93576.16588573981], [1745452800000, 93605.45230873208], [1745539200000, 93872.81422867288], [1745625600000, 94773.11200643536], [1745712000000, 94644.06637120107], [1745798400000, 93809.33781968223], [1745884800000, 95030.60645474444], [1745971200000, 94256.35946318062], [1746057600000, 94235.75331048167], [1746144000000, 96426.94522273027], [1746230400000, 96855.5681343944], [1746316800000, 95922.86842404422], [1746403200000, 94326.62048529249], [1746489600000, 94758.8237105546], [1746576000000, 96854.53198815876], [1746662400000, 97026.49376966801], [1746748800000, 103076.27555512934], [1746835200000, 102962.54045692299], [1746921600000, 104630.8792994166], [1747008000000, 103994.061616746], [1747094400000, 102876.8304286011], [1747180800000, 104184.49039270742], [1747267200000, 103594.42575090709], [1747353600000, 103708.85136423641], [1747440000000, 103556.03493982446], [1747526400000, 103212.36483885496], [1747612800000, 106030.6376831359], [1747699200000, 105629.41580436694], [1747785600000, 106786.71995834043], [1747872000000, 109665.86371625263], [1747958400000, 111560.356938144], [1748044800000, 107216.66856870624], [1748131200000, 107831.36374380375], [1748217600000, 108861.81037744327], [1748304000000, 109377.71513263129], [1748390400000, 109068.45694901445], [1748476800000, 107838.18431100152], [1748563200000, 105745.41660358038], [1748649600000, 104010.91956242644], [1748736000000, 104687.50742934884], [1748822400000, 105710.00593822816], [1748908800000, 105884.74263221149], [1748995200000, 105434.47745144971], [1749081600000, 104812.9182188067], [1749168000000, 101650.7387545425], [1749254400000, 104409.74967959142], [1749340800000, 105681.4546141758], [1749427200000, 105692.24740699006], [1749513600000, 110261.57485948496], [1749600000000, 110212.73252109604], [1749686400000, 108679.9760916168], [1749772800000, 105979.22902375912], [1749859200000, 106045.56440819203], [1749945600000, 105482.90611628917], [1750032000000, 105554.49383061715], [1750118400000, 106951.2720181497], [1750204800000, 104683.42479835715], [1750291200000, 104722.695052907], [1750377600000, 104690.65002458123], [1750464000000, 103290.105144757], [1750550400000, 101532.5683847329], [1750636800000, 100852.58264648831], [1750723200000, 105511.62437933135], [1750809600000, 105976.06929808448], [1750896000000, 107238.53045016268], [1750982400000, 106984.01253775663], [1751068800000, 107078.91560644074], [1751155200000, 107331.58548463577], [1751241600000, 108396.61631317894], [1751328000000, 107132.79910701896], [1751414400000, 105613.39974163055], [1751500800000, 108824.44423167943], [1751587200000, 109602.20483914016], [1751673600000, 108040.8919400104], [1751760000000, 108217.46849992426], [1751846400000, 109215.19771840284], [1751932800000, 108300.71675785031], [1752019200000, 108953.19187727802], [1752105600000, 111327.53054245669], [1752192000000, 115879.65030112496], [1752278400000, 117571.02510036016], [1752364800000, 117418.95745007684], [1752451200000, 119117.55666327637], [1752537600000, 119833.67446712355], [1752624000000, 117678.19493404306], [1752710400000, 118748.1627367753], [1752796800000, 119445.36520434043], [1752883200000, 117988.94664455787], [1752969600000, 117901.62655900871], [1753056000000, 117256.9208222684], [1753142400000, 117482.46977767294], [1753228800000, 119955.79570607653], [1753315200000, 118629.05588130427], [1753401600000, 118354.43517438594], [1753488000000, 117540.80837085741], [1753574400000, 117959.54234360624], [1753660800000, 119418.91405141471], [1753747200000, 118003.30201607826], [1753833600000, 117853.30892863822], [1753920000000, 117833.24087995925], [1754006400000, 115700.00243915782], [1754092800000, 113234.6051343189], [1754179200000, 112554.90232221723], [1754265600000, 114199.10966460757], [1754352000000, 115138.68613070177], [1754438400000, 114128.35408881678], [1754524800000, 115022.09576830892], [1754611200000, 117463.47451085235], [1754697600000, 116688.36663186055], [1754784000000, 116510.08393213755], [1754870400000, 119266.92516880555], [1754956800000, 118773.79960860992], [1755043200000, 120202.53485503166], [1755129600000, 123560.99363577305], [1755216000000, 118405.59579823953], [1755302400000, 117339.79190213277], [1755388800000, 117501.21653394958], [1755475200000, 117542.83687778088], [1755561600000, 116256.41276740946], [1755648000000, 112778.34483555844], [1755734400000, 114252.39755195397], [1755820800000, 112414.39987336512], [1755907200000, 116834.24948202295], [1755993600000, 115359.98346714744], [1756080000000, 113399.54847314971], [1756166400000, 110185.35443900425], [1756252800000, 111842.70999260596], [1756339200000, 111216.08479629169], [1756425600000, 112525.59740669793], [1756512000000, 108480.30666639366], [1756598400000, 108781.95727925687], [1756684800000, 108253.36092385623], [1756771200000, 109162.68557992298], [1756857600000, 111190.18209845416], [1756944000000, 111711.51977725117], [1757030400000, 110724.736377486], [1757116800000, 110662.18112628513], [1757203200000, 110209.1888247784], [1757289600000, 111131.9923868407], [1757376000000, 112025.12878118771], [1757462400000, 111547.43956434788], [1757548800000, 113975.32489468766], [1757635200000, 115503.16663193036], [1757721600000, 116160.14344594491], [1757808000000, 115970.58488443034], [1757894400000, 115373.55555886829], [1757980800000, 115397.25272727509], [1758067200000, 116762.8496864193], [1758153600000, 116455.94648225319], [1758240000000, 117145.49508952006], [1758326400000, 115655.81046441344], [1758412800000, 115715.51536781774], [1758499200000, 115304.47999407038], [1758585600000, 112696.74101711863], [1758672000000, 112022.16587861195], [1758758400000, 113320.56908541008], [1758844800000, 108963.53013595635], [1758931200000, 109710.20874667744], [1759017600000, 109654.81021075726], [1759104000000, 112142.57362752674], [1759190400000, 114309.15041119447], [1759276800000, 114024.22783550054], [1759363200000, 118503.24451752483], [1759449600000, 120611.71911591051], [1759536000000, 122250.15186842803], [1759622400000, 122380.93708463266], [1759708800000, 123506.18520027678], [1759795200000, 124773.50823074432], [1759881600000, 121518.75593575071], [1759968000000, 123352.50487523204], [1760054400000, 121698.03066778315], [1760140800000, 113201.74064138904], [1760227200000, 110853.11663883903], [1760313600000, 115189.5714637257], [1760400000000, 115222.28302116522], [1760486400000, 113156.56943826913], [1760572800000, 110708.66960879423], [1760659200000, 108076.72862033188], [1760745600000, 106443.61194984635], [1760832000000, 107156.00337647724], [1760918400000, 108621.134857428], [1761004800000, 110608.5714932665], [1761091200000, 108486.10262716639], [1761177600000, 107618.4266715404], [1761264000000, 110048.51827291629], [1761350400000, 110997.80437129698], [1761436800000, 111620.3093731354], [1761523200000, 114476.01227508577], [1761609600000, 114182.79442806762], [1761696000000, 112950.34863259472], [1761782400000, 110046.66925837283], [1761868800000, 108240.76528725718], [1761955200000, 109573.90555629115], [1762041600000, 110014.13556776087], [1762128000000, 110650.2092823146], [1762214400000, 106521.08673825761], [1762300800000, 101635.2740227234], [1762387200000, 103877.95965955159], [1762473600000, 101322.6402945857], [1762560000000, 103396.084215925], [1762646400000, 102290.13714655167], [1762732800000, 104709.67861656273], [1762819200000, 105909.07272321742], [1762905600000, 102960.77564500563], [1762992000000, 101521.70859453593], [1763078400000, 99730.4533956204], [1763164800000, 94456.39368235337], [1763251200000, 95508.31019889197], [1763337600000, 94411.32947182967], [1763424000000, 92036.7255045672], [1763510400000, 92819.75921500899], [1763596800000, 91363.27838693369], [1763683200000, 86649.97257918229], [1763769600000, 85051.8019295002], [1763856000000, 84682.62429147748], [1763942400000, 86783.84766839583], [1764028800000, 88229.35740719768], [1764115200000, 87310.33159950442], [1764201600000, 90474.22677969698], [1764288000000, 91279.06057176423], [1764374400000, 90950.37695910994], [1764460800000, 90841.45258193677], [1764547200000, 90406.28448571145], [1764633600000, 86281.49519776918], [1764720000000, 91344.73275150165], [1764806400000, 93619.43750817103], [1764892800000, 92140.70419795791], [1764979200000, 89307.09154512963], [1765065600000, 89244.7620814118], [1765152000000, 90162.90714007126], [1765238400000, 90618.0535204608], [1765324800000, 92723.21372069631], [1765411200000, 92005.13714957413], [1765497600000, 92494.17691640415], [1765584000000, 90307.26028567803], [1765670400000, 90257.4292885891], [1765756800000, 88230.77409367911], [1765843200000, 86413.9190195637], [1765929600000, 87821.88919109134], [1766016000000, 86064.94716216], [1766102400000, 85450.3312009302], [1766188800000, 88103.86075721023], [1766275200000, 88347.94310567998], [1766361600000, 88577.42038358838], [1766448000000, 88491.12020788102], [1766534400000, 87406.43636737975], [1766620800000, 87642.60888119951], [1766707200000, 87229.78066010943], [1766793600000, 87305.95655961394], [1766880000000, 87807.003210775], [1766966400000, 87822.90829076794], [1767052800000, 87156.56266080117], [1767139200000, 88414.62856073362], [1767225600000, 87520.18048742875], [1767312000000, 88727.67004249741], [1767398400000, 89926.27924953419], [1767484800000, 90593.85443180417], [1767571200000, 91373.21588108438], [1767657600000, 93926.7956485658], [1767744000000, 93666.86387314305], [1767830400000, 91257.15544035907], [1767916800000, 90983.51578142625], [1768003200000, 90504.89560340019], [1768089600000, 90442.01907847001], [1768176000000, 90819.36598904192], [1768262400000, 91134.96917951507], [1768348800000, 95260.4422971001], [1768435200000, 97007.78078881276], [1768521600000, 95584.82797878512], [1768608000000, 95516.07771987123], [1768694400000, 95099.53192554631], [1768780800000, 93752.70577188236], [1768867200000, 92558.46334372147], [1768953600000, 88312.84053255555], [1769040000000, 89354.34377512129], [1769126400000, 89443.39744146909], [1769212800000, 89412.39849953113], [1769299200000, 89170.87364531498], [1769385600000, 86548.32213469829], [1769472000000, 88307.8612070438], [1769558400000, 89204.22239644526], [1769644800000, 89162.09701574955], [1769731200000, 84570.40906135936], [1769817600000, 84141.77856967277], [1769904000000, 78725.85853884545], [1769990400000, 76937.06406636834], [1770076800000, 78767.65815345927], [1770163200000, 75638.95670207398], [1770249600000, 73172.29203248928], [1770336000000, 62853.69038445987], [1770422400000, 70523.95417035831], [1770508800000, 69296.80677355142], [1770595200000, 70542.37329463876], [1770681600000, 70096.40692272567], [1770768000000, 68779.90981269129], [1770854400000, 66937.58141157958], [1770940800000, 66184.57765470445], [1771027200000, 68838.87490510389], [1771113600000, 69765.59638824302], [1771200000000, 68716.58337486399], [1771286400000, 68907.78353606178], [1771372800000, 67489.45540267964], [1771459200000, 66456.3537620677], [1771545600000, 66918.68417467622], [1771632000000, 67970.29403133177], [1771718400000, 67977.90904199042], [1771804800000, 67585.11718938159], [1771891200000, 64577.553200674425], [1771977600000, 64074.11098528222], [1772064000000, 67947.39185585188], [1772150400000, 67469.06040327046], [1772236800000, 65883.99096235317], [1772323200000, 67008.45435746174], [1772409600000, 65713.4989891121], [1772496000000, 68864.03691918531], [1772582400000, 68321.6178484252], [1772668800000, 72669.7701652216], [1772755200000, 70874.98687140146], [1772841600000, 68148.28339966535], [1772928000000, 67271.1907777184], [1773014400000, 66036.15782362667], [1773100800000, 68459.31537095344], [1773187200000, 69883.00887579883], [1773273600000, 70226.818790692], [1773360000000, 70544.42535461926], [1773446400000, 70965.28228600459], [1773532800000, 71217.1010283798], [1773619200000, 72681.9132538886], [1773705600000, 74858.14870100339], [1773792000000, 73926.27899152413], [1773878400000, 71255.86350265636], [1773964800000, 69871.4514796119], [1774011385000, 70307.22920535825]], 'market_caps': [[1742515200000, 1672550706502.8184], [1742601600000, 1666749159154.2927], [1742688000000, 1662574363663.653], [1742774400000, 1702009594329.4495], [1742860800000, 1732715331970.134], [1742947200000, 1735368473904.4885], [1743033600000, 1724854479045.6724], [1743120000000, 1729729987159.4822], [1743206400000, 1673182800974.1038], [1743292800000, 1640665503855.1438], [1743379200000, 1633996304187.2593], [1743465600000, 1635076581047.3545], [1743552000000, 1690602036035.04], [1743638400000, 1637358764747.381], [1743724800000, 1652537223074.958], [1743811200000, 1664234880198.049], [1743897600000, 1656020067997.187], [1743984000000, 1555325260787.2627], [1744070400000, 1581407565278.352], [1744156800000, 1515042499757.3254], [1744243200000, 1640567909122.172], [1744329600000, 1580023209138.0547], [1744416000000, 1655868880454.1702], [1744502400000, 1693600655371.0874], [1744588800000, 1658923208081.8682], [1744675200000, 1677843510120.269], [1744761600000, 1660749023283.0562], [1744848000000, 1670497569762.047], [1744934400000, 1686226810049.1836], [1745020800000, 1676373197914.5117], [1745107200000, 1690090596771.3958], [1745193600000, 1689008667806.3804], [1745280000000, 1735703747771.06], [1745366400000, 1858587811717.8286], [1745452800000, 1858660302322.256], [1745539200000, 1864298110563.3408], [1745625600000, 1882121595175.8462], [1745712000000, 1879131951239.1846], [1745798400000, 1862772247122.064], [1745884800000, 1887067388174.3481], [1745971200000, 1870818389258.4038], [1746057600000, 1871350362569.0933], [1746144000000, 1914884389769.3945], [1746230400000, 1923251765866.1472], [1746316800000, 1904894886394.57], [1746403200000, 1872812442453.0322], [1746489600000, 1882511286487.958], [1746576000000, 1923643840814.599], [1746662400000, 1927134557858.269], [1746748800000, 2047883753852.6929], [1746835200000, 2045046445523.5242], [1746921600000, 2077132539531.3464], [1747008000000, 2065659960471.3655], [1747094400000, 2044347271866.1707], [1747180800000, 2069356072124.024], [1747267200000, 2057798367292.5637], [1747353600000, 2060142559914.034], [1747440000000, 2057725640290.0767], [1747526400000, 2050318521477.805], [1747612800000, 2104889720872.8306], [1747699200000, 2098485415895.0496], [1747785600000, 2121778617273.821], [1747872000000, 2178838967665.505], [1747958400000, 2214712145787.249], [1748044800000, 2131595896624.4407], [1748131200000, 2142540077685.2197], [1748217600000, 2163072841533.6133], [1748304000000, 2173059855839.4187], [1748390400000, 2167551887130.0073], [1748476800000, 2143342706888.307], [1748563200000, 2101348752694.3137], [1748649600000, 2066830946978.0637], [1748736000000, 2080467809295.7695], [1748822400000, 2101178071590.9749], [1748908800000, 2104229403094.936], [1748995200000, 2095294001281.4797], [1749081600000, 2083148839111.2068], [1749168000000, 2020294099992.3677], [1749254400000, 2075175500201.4253], [1749340800000, 2100553336902.5076], [1749427200000, 2100654769399.4705], [1749513600000, 2191877481230.9468], [1749600000000, 2189350055406.3333], [1749686400000, 2159529375273.4956], [1749772800000, 2107911943768.2988], [1749859200000, 2107973087547.7922], [1749945600000, 2097486541223.27], [1750032000000, 2098499110552.6216], [1750118400000, 2127895470544.7178], [1750204800000, 2080968120976.949], [1750291200000, 2081677732261.6853], [1750377600000, 2081355279873.408], [1750464000000, 2054120245608.2085], [1750550400000, 2017415966695.5278], [1750636800000, 2005179769771.7349], [1750723200000, 2097741233586.5918], [1750809600000, 2107110352429.8032], [1750896000000, 2132141147369.0017], [1750982400000, 2127292099754.93], [1751068800000, 2129020567385.9595], [1751155200000, 2134239999929.6584], [1751241600000, 2155183166489.813], [1751328000000, 2130471589191.581], [1751414400000, 2100087563077.9324], [1751500800000, 2163835371770.0977], [1751587200000, 2179664531219.9346], [1751673600000, 2148601712907.3433], [1751760000000, 2152344091389.654], [1751846400000, 2171497503296.0474], [1751932800000, 2153777588647.4504], [1752019200000, 2167049398056.7417], [1752105600000, 2215210888568.426], [1752192000000, 2303292356999.7437], [1752278400000, 2338612196961.7437], [1752364800000, 2335485977830.673], [1752451200000, 2369050366835.5605], [1752537600000, 2383825813673.847], [1752624000000, 2341223394839.9204], [1752710400000, 2363194640209.576], [1752796800000, 2376237382764.3013], [1752883200000, 2347165317624.536], [1752969600000, 2345398337785.541], [1753056000000, 2333757287859.664], [1753142400000, 2337365497467.1313], [1753228800000, 2387516761560.4927], [1753315200000, 2359931875300.5244], [1753401600000, 2354764508342.9937], [1753488000000, 2338855554998.7812], [1753574400000, 2346959472845.027], [1753660800000, 2376524838793.0137], [1753747200000, 2349472897426.4688], [1753833600000, 2345126504020.1143], [1753920000000, 2343717963709.7124], [1754006400000, 2302199162425.1206], [1754092800000, 2253609880959.403], [1754179200000, 2240413983638.112], [1754265600000, 2272802075267.0376], [1754352000000, 2292395156144.1514], [1754438400000, 2271583255077.356], [1754524800000, 2289295036528.6577], [1754611200000, 2337732858703.5435], [1754697600000, 2323026541073.3213], [1754784000000, 2318815857401.68], [1754870400000, 2374097296837.8896], [1754956800000, 2364060561672.9995], [1755043200000, 2392854421745.6157], [1755129600000, 2458895200752.567], [1755216000000, 2360043737045.272], [1755302400000, 2335290383260.173], [1755388800000, 2339465736068.208], [1755475200000, 2340648324181.828], [1755561600000, 2313556987528.4634], [1755648000000, 2245419916215.7417], [1755734400000, 2274471285844.184], [1755820800000, 2238121481749.57], [1755907200000, 2326174803320.612], [1755993600000, 2296786080139.701], [1756080000000, 2259663171125.389], [1756166400000, 2194453712375.598], [1756252800000, 2227025695775.593], [1756339200000, 2215255294289.9937], [1756425600000, 2239422945686.892], [1756512000000, 2160278651486.2852], [1756598400000, 2166165747945.1812], [1756684800000, 2155694976689.5986], [1756771200000, 2174100506466.4321], [1756857600000, 2212595221503.454], [1756944000000, 2225365905592.233], [1757030400000, 2204051936301.3257], [1757116800000, 2204045604630.5625], [1757203200000, 2195288669199.568], [1757289600000, 2213764479139.3647], [1757376000000, 2231763512226.867], [1757462400000, 2222026777598.0474], [1757548800000, 2270241314652.7144], [1757635200000, 2299764311655.674], [1757721600000, 2314347371939.946], [1757808000000, 2310166037871.29], [1757894400000, 2297459118244.424], [1757980800000, 2297977599504.5527], [1758067200000, 2325326932460.9644], [1758153600000, 2321583680138.891], [1758240000000, 233

In [18]:
coins_hist=pd.DataFrame(coins_hist)
coins_hist['date']=coins_hist['date'].dt.date
coins_hist

     coin_id        date     price_usd
0    bitcoin  2025-03-21  84270.843590
1    bitcoin  2025-03-22  84009.532918
2    bitcoin  2025-03-23  83793.308542
3    bitcoin  2025-03-24  85787.709149
4    bitcoin  2025-03-25  87327.729697
..       ...         ...           ...
361  bitcoin  2026-03-17  74858.148701
362  bitcoin  2026-03-18  73926.278992
363  bitcoin  2026-03-19  71255.863503
364  bitcoin  2026-03-20  69871.451480
365  bitcoin  2026-03-20  70307.229205

[366 rows x 3 columns]

In [19]:
coins_hist.to_csv("Historical_coins.csv",index=False)

**Extracting oilprice**

In [20]:
import pandas as pd
oil_df = pd.read_csv("https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv")
oil_df

             Date  Price
0      1986-01-02  25.56
1      1986-01-03  26.00
2      1986-01-06  26.53
3      1986-01-07  25.85
4      1986-01-08  25.87
...           ...    ...
10114  2026-03-10  83.71
10115  2026-03-11  86.80
10116  2026-03-12  95.61
10117  2026-03-13  98.48
10118  2026-03-16  93.39

[10119 rows x 2 columns]

In [21]:
oil_df['Date'] = pd.to_datetime(oil_df['Date'])

oil_df

            Date  Price
0     1986-01-02  25.56
1     1986-01-03  26.00
2     1986-01-06  26.53
3     1986-01-07  25.85
4     1986-01-08  25.87
...          ...    ...
10114 2026-03-10  83.71
10115 2026-03-11  86.80
10116 2026-03-12  95.61
10117 2026-03-13  98.48
10118 2026-03-16  93.39

[10119 rows x 2 columns]

In [22]:
oil_df = oil_df[(oil_df['Date'] >= '2020-01-01') & (oil_df['Date'] <= '2026-01-31')]
oil_df

            Date  Price
8569  2020-01-02  61.17
8570  2020-01-03  63.00
8571  2020-01-06  63.27
8572  2020-01-07  62.70
8573  2020-01-08  59.65
...          ...    ...
10084 2026-01-26  60.46
10085 2026-01-27  62.04
10086 2026-01-28  62.75
10087 2026-01-29  64.77
10088 2026-01-30  64.50

[1520 rows x 2 columns]

In [23]:
oil_df['Date']=oil_df['Date'].dt.date
oil_df

/tmp/ipykernel_1156/1069987075.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oil_df['Date']=oil_df['Date'].dt.date

             Date  Price
8569   2020-01-02  61.17
8570   2020-01-03  63.00
8571   2020-01-06  63.27
8572   2020-01-07  62.70
8573   2020-01-08  59.65
...           ...    ...
10084  2026-01-26  60.46
10085  2026-01-27  62.04
10086  2026-01-28  62.75
10087  2026-01-29  64.77
10088  2026-01-30  64.50

[1520 rows x 2 columns]

In [24]:
oil_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1520 entries, 8569 to 10088
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1520 non-null   object
 1   Price   1520 non-null   float64
dtypes: float64(1), object(1)
memory usage: 67.9+ KB

**Extracting the stick data**

In [25]:
import yfinance as yf
import pandas as pd

# Choose indices
tickers = ["^GSPC", "^IXIC", "^NSEI"]
start_date = "2020-01-01"
end_date = "2026-01-12"

# Download historical data
stocks_df = yf.download(tickers, start=start_date, end=end_date, group_by="ticker")
stocks_df.head()

/tmp/ipykernel_1156/1369541528.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  stocks_df = yf.download(tickers, start=start_date, end=end_date, group_by="ticker")
[*********************100%***********************]  3 of 3 completed

Ticker            ^IXIC                                                       \
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  9039.459961  9093.429688  9010.889648  9092.190430  2.862700e+09
2020-01-03  8976.429688  9065.759766  8976.429688  9020.769531  2.586520e+09
2020-01-06  8943.500000  9072.410156  8943.500000  9071.469727  2.810450e+09
2020-01-07  9076.639648  9091.929688  9042.549805  9068.580078  2.381740e+09

Ticker             ^NSEI                                                      \
Price               Open          High           Low         Close    Volume
Date
2020-01-01  12202.150391  12222.200195  12165.299805  12182.500000  304100.0
2020-01-02  12198.549805  12289.900391  12195.250000  12282.200195  407700.0
2020-01-03  12261.099609  12265.599609  12191.349609  12226.650391  428800.0
2020-01-06  12170.599609  12179.099609  11974.200195  11993.049805  396500.0
2020-01-07  12079.099609  12152.150391  12005.349609  12052.950195  447800.0

Ticker            ^GSPC
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  3244.669922  3258.139893  3235.530029  3257.850098  3.459930e+09
2020-01-03  3226.360107  3246.149902  3222.340088  3234.850098  3.484700e+09
2020-01-06  3217.550049  3246.840088  3214.639893  3246.280029  3.702460e+09
2020-01-07  3241.860107  3244.909912  3232.429932  3237.179932  3.435910e+09

In [26]:
nsei = stocks_df['^NSEI'].reset_index() # collect 3 ticker data similarly , add a new column ticker and then concat them.
nsei['ticker']="^NSEI"
nsei

Price,Date,Open,High,Low,Close,Volume,ticker
0,2020-01-01,12202.150391,12222.200195,12165.299805,12182.500000,304100.0,^NSEI
1,2020-01-02,12198.549805,12289.900391,12195.250000,12282.200195,407700.0,^NSEI
2,2020-01-03,12261.099609,12265.599609,12191.349609,12226.650391,428800.0,^NSEI
3,2020-01-06,12170.599609,12179.099609,11974.200195,11993.049805,396500.0,^NSEI
4,2020-01-07,12079.099609,12152.150391,12005.349609,12052.950195,447800.0,^NSEI
...,...,...,...,...,...,...,...
1558,2026-01-05,26333.699219,26373.199219,26210.050781,26250.300781,338800.0,^NSEI
1559,2026-01-06,26189.699219,26273.949219,26124.750000,26178.699219,383000.0,^NSEI
1560,2026-01-07,26143.099609,26187.150391,26067.900391,26140.750000,338200.0,^NSEI
1561,2026-01-08,26106.500000,26133.199219,25858.449219,25876.849609,328500.0,^NSEI
1562,2026-01-09,25840.400391,25940.599609,25623.000000,25683.300781,348800.0,^NSEI

In [27]:
nsei.isnull().sum()

Price
Date       0
Open      70
High      70
Low       70
Close     70
Volume    70
ticker     0
dtype: int64

In [28]:
nsei.dropna(inplace=True)
nsei.isnull().sum()

Price
Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
ticker    0
dtype: int64

In [29]:
nsei.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1493 entries, 0 to 1562
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1493 non-null   datetime64[ns]
 1   Open    1493 non-null   float64
 2   High    1493 non-null   float64
 3   Low     1493 non-null   float64
 4   Close   1493 non-null   float64
 5   Volume  1493 non-null   float64
 6   ticker  1493 non-null   object
dtypes: datetime64[ns](1), float64(5), object(1)
memory usage: 93.3+ KB

In [30]:
ixic = stocks_df["^IXIC"].reset_index()
ixic['ticker']="^IXIC"
ixic

Price,Date,Open,High,Low,Close,Volume,ticker
0,2020-01-01,NaN,NaN,NaN,NaN,NaN,^IXIC
1,2020-01-02,9039.459961,9093.429688,9010.889648,9092.190430,2.862700e+09,^IXIC
2,2020-01-03,8976.429688,9065.759766,8976.429688,9020.769531,2.586520e+09,^IXIC
3,2020-01-06,8943.500000,9072.410156,8943.500000,9071.469727,2.810450e+09,^IXIC
4,2020-01-07,9076.639648,9091.929688,9042.549805,9068.580078,2.381740e+09,^IXIC
...,...,...,...,...,...,...,...
1558,2026-01-05,23449.669922,23476.509766,23332.230469,23395.820312,8.737320e+09,^IXIC
1559,2026-01-06,23446.960938,23559.150391,23389.570312,23547.169922,9.012640e+09,^IXIC
1560,2026-01-07,23544.890625,23723.369141,23504.210938,23584.279297,8.396920e+09,^IXIC
1561,2026-01-08,23548.880859,23558.169922,23353.460938,23480.019531,7.723140e+09,^IXIC
1562,2026-01-09,23496.210938,23721.150391,23426.480469,23671.349609,8.124420e+09,^IXIC

In [31]:
ixic.isnull().sum()

Price
Date       0
Open      49
High      49
Low       49
Close     49
Volume    49
ticker     0
dtype: int64

In [32]:
ixic.dropna(inplace=True)
ixic.isnull().sum()

Price
Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
ticker    0
dtype: int64

In [33]:
ixic.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1514 entries, 1 to 1562
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1514 non-null   datetime64[ns]
 1   Open    1514 non-null   float64
 2   High    1514 non-null   float64
 3   Low     1514 non-null   float64
 4   Close   1514 non-null   float64
 5   Volume  1514 non-null   float64
 6   ticker  1514 non-null   object
dtypes: datetime64[ns](1), float64(5), object(1)
memory usage: 94.6+ KB

In [34]:
gspc = stocks_df["^GSPC"].reset_index()
gspc['ticker']='^GSPC'
gspc

Price,Date,Open,High,Low,Close,Volume,ticker
0,2020-01-01,NaN,NaN,NaN,NaN,NaN,^GSPC
1,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09,^GSPC
2,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09,^GSPC
3,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09,^GSPC
4,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09,^GSPC
...,...,...,...,...,...,...,...
1558,2026-01-05,6892.189941,6920.379883,6891.560059,6902.049805,5.771930e+09,^GSPC
1559,2026-01-06,6908.029785,6948.689941,6904.020020,6944.819824,5.509680e+09,^GSPC
1560,2026-01-07,6945.069824,6965.689941,6919.189941,6920.930176,5.214480e+09,^GSPC
1561,2026-01-08,6914.109863,6931.279785,6899.330078,6921.459961,5.333200e+09,^GSPC
1562,2026-01-09,6927.830078,6978.359863,6917.640137,6966.279785,5.163900e+09,^GSPC

In [35]:
gspc.isnull().sum()

Price
Date       0
Open      49
High      49
Low       49
Close     49
Volume    49
ticker     0
dtype: int64

In [36]:
gspc.dropna(inplace=True)
gspc.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1514 entries, 1 to 1562
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1514 non-null   datetime64[ns]
 1   Open    1514 non-null   float64
 2   High    1514 non-null   float64
 3   Low     1514 non-null   float64
 4   Close   1514 non-null   float64
 5   Volume  1514 non-null   float64
 6   ticker  1514 non-null   object
dtypes: datetime64[ns](1), float64(5), object(1)
memory usage: 94.6+ KB

In [37]:
stocks=pd.concat([nsei,ixic,gspc])
stocks

Price,Date,Open,High,Low,Close,Volume,ticker
0,2020-01-01,12202.150391,12222.200195,12165.299805,12182.500000,3.041000e+05,^NSEI
1,2020-01-02,12198.549805,12289.900391,12195.250000,12282.200195,4.077000e+05,^NSEI
2,2020-01-03,12261.099609,12265.599609,12191.349609,12226.650391,4.288000e+05,^NSEI
3,2020-01-06,12170.599609,12179.099609,11974.200195,11993.049805,3.965000e+05,^NSEI
4,2020-01-07,12079.099609,12152.150391,12005.349609,12052.950195,4.478000e+05,^NSEI
...,...,...,...,...,...,...,...
1558,2026-01-05,6892.189941,6920.379883,6891.560059,6902.049805,5.771930e+09,^GSPC
1559,2026-01-06,6908.029785,6948.689941,6904.020020,6944.819824,5.509680e+09,^GSPC
1560,2026-01-07,6945.069824,6965.689941,6919.189941,6920.930176,5.214480e+09,^GSPC
1561,2026-01-08,6914.109863,6931.279785,6899.330078,6921.459961,5.333200e+09,^GSPC
1562,2026-01-09,6927.830078,6978.359863,6917.640137,6966.279785,5.163900e+09,^GSPC

In [38]:
stocks['Date']=stocks['Date'].dt.date

In [39]:
stocks.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4521 entries, 0 to 1562
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    4521 non-null   object
 1   Open    4521 non-null   float64
 2   High    4521 non-null   float64
 3   Low     4521 non-null   float64
 4   Close   4521 non-null   float64
 5   Volume  4521 non-null   float64
 6   ticker  4521 non-null   object
dtypes: float64(5), object(2)
memory usage: 282.6+ KB

# **SQL DATABASE **

In [40]:
import sqlite3

conn = sqlite3.connect("cmarket.db")
cursor = conn.cursor()

In [41]:
conn.execute(''' create table crypto_currencies(
  id varchar(50) primary key,symbol varchar(10),name varchar(100),current_price decimal(18,6),market_cap bigint,
  market_cap_rank int,total_volume bigint,circulating_supply decimal(20,6),total_supply decimal(20,6),ath decimal(18,6),
  atl decimal(18,6),date date
)


''')

In [42]:
conn.execute(''' create table crypto_prices(coin_id varchar(50),date date,price_usd decimal(18,6),
foreign key(coin_id) references Cryptocurrencies(id))''')

In [43]:
conn.execute(''' create table oilprice(date date primary key,price decimal(18,6))''')

In [44]:
conn.execute(''' create table stock_prices(date date,open decimal(18,6),high decimal(18,6),low decimal(18,6),
close decimal(18,6),volume bigint,ticker varchar(20))''')

In [45]:
for index,row in oil_df.iterrows():
  conn.execute('''insert into oilprice values(?,?)''',(row['Date'],row['Price']))
conn.commit()

In [46]:
result=pd.read_sql('''select * from oilprice''',conn)
result

            date  price
0     2020-01-02  61.17
1     2020-01-03  63.00
2     2020-01-06  63.27
3     2020-01-07  62.70
4     2020-01-08  59.65
...          ...    ...
1515  2026-01-26  60.46
1516  2026-01-27  62.04
1517  2026-01-28  62.75
1518  2026-01-29  64.77
1519  2026-01-30  64.50

[1520 rows x 2 columns]

In [47]:
for index,row in crypto_filter.iterrows():
  conn.execute(''' insert into crypto_currencies values(?,?,?,?,?,?,?,?,?,?,?,?)''',
               (row['id'],row['symbol'],row['name'],row['current_price'],row["market_cap"],row["market_cap_rank"],row["total_volume"],
               row["circulating_supply"],row["total_supply"],row["ath"],row["atl"],row["last_updated"]))
conn.commit()

In [48]:
for index,row in coins_hist.iterrows():
  conn.execute('''insert into crypto_prices values(?,?,?)''',(row['coin_id'],row['date'],row['price_usd']))
conn.commit()

In [49]:
for inde,row in stocks.iterrows():
  conn.execute('''insert into stock_prices values(?,?,?,?,?,?,?)''',(row['Date'],row['Open'],row['High'],row['Low'],row['Close'],row['Volume'],row['ticker']))
conn.commit()

# **CRYPTOCURRENCIES**

**1. Find the top 3 cryptocurrencies by market cap.**

In [50]:
c1=pd.read_sql('''select * from crypto_currencies order by market_cap desc limit 3''',conn)
c1

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,date
0,bitcoin,btc,Bitcoin,70412.000000,1407570518748,1,40857128560,2.000304e+07,2.000304e+07,126080.00,67.810000,2026-03-20
1,ethereum,eth,Ethereum,2143.510000,258400050398,2,21204807932,1.206918e+08,1.206918e+08,4946.05,0.432979,2026-03-20
2,tether,usdt,Tether,0.999822,184152928583,3,68123889445,1.841833e+11,1.896502e+11,1.32,0.572521,2026-03-20

**2. List all coins where circulating supply exceeds 90% of total supply.**

In [51]:
c2=pd.read_sql('''select id,name,circulating_supply,total_supply from crypto_currencies where circulating_supply > 0.90 * total_supply''',conn)
c2

                    id                 name  circulating_supply  total_supply
0              bitcoin              Bitcoin        2.000304e+07  2.000304e+07
1             ethereum             Ethereum        1.206918e+08  1.206918e+08
2               tether               Tether        1.841833e+11  1.896502e+11
3          binancecoin                  BNB        1.363577e+08  1.363577e+08
4             usd-coin                 USDC        7.920483e+10  7.920753e+10
..                 ...                  ...                 ...           ...
402              metal            Metal DAO        8.915320e+07  8.915320e+07
403          gradients            Gradients        4.154498e+06  4.154498e+06
404  noble-dollar-usdn  Noble Dollar (USDN)        2.425792e+07  2.425792e+07
405           medibloc             Medibloc        1.064404e+10  1.143426e+10
406            honey-3                Honey        2.421902e+07  2.421903e+07

[407 rows x 4 columns]

**3. Get coins that are within 10% of their all-time-high (ATH).**

In [52]:
c3=pd.read_sql('''select * from crypto_currencies where current_price >= 0.9 * ath''',conn)
c3

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,date
0,usd-coin,usdc,USDC,0.999993,79200146079,6,5.019216e+09,7.920483e+10,7.920753e+10,1.043,0.877647,2026-03-20
1,figure-heloc,figr_heloc,Figure Heloc,1.002000,15870605852,9,3.305275e+08,1.584354e+10,1.584354e+10,1.049,0.155357,2026-03-20
2,usds,usds,USDS,0.999855,11499134711,12,7.334107e+06,1.150079e+10,1.150079e+10,1.057,0.948265,2026-03-20
3,leo-token,leo,LEO Token,9.200000,8477054755,16,8.207850e+05,9.210671e+08,9.852395e+08,10.140,0.799859,2026-03-20
4,ethena-usde,usde,Ethena USDe,1.000000,5924913582,19,1.009972e+08,5.924977e+09,5.924977e+09,1.034,0.929486,2026-03-20
...,...,...,...,...,...,...,...,...,...,...,...,...
89,usa,usat,USAT,1.000000,27752254,681,2.081064e+06,2.775204e+07,2.775204e+07,1.002,0.996080,2026-03-20
90,metamask-usd,musd,MetaMask USD,0.999935,27158777,695,4.552642e+06,2.715694e+07,2.715694e+07,1.066,0.979806,2026-03-20
91,invesco-qqq-etf-ondo-tokenized-etf,qqqon,Invesco QQQ ETF (Ondo Tokenized ETF),592.780000,26862915,704,1.642005e+06,4.531678e+04,4.531678e+04,641.530,559.710000,2026-03-20
92,monerium-eur-money,eure,Monerium EUR emoney [OLD],1.160000,26599019,708,1.077695e+06,2.298157e+07,2.298157e+07,1.210,0.951958,2026-03-20
93,noble-dollar-usdn,usdn,Noble Dollar (USDN),0.999998,24257878,743,1.234140e+05,2.425792e+07,2.425792e+07,1.015,0.956184,2026-03-20

**4. Find the average market cap rank of coins with volume above $1B.**

In [53]:
c4=pd.read_sql(''' select name,avg(market_cap_rank) from crypto_currencies where total_volume>1000000000''', conn)
c4

      name  avg(market_cap_rank)
0  Bitcoin                  6.25

**5. Get the most recently updated coin.**

In [54]:
c5=pd.read_sql('''select name,date from crypto_currencies order by date desc limit 10''',conn)
c5

           name        date
0       Bitcoin  2026-03-20
1      Ethereum  2026-03-20
2        Tether  2026-03-20
3           XRP  2026-03-20
4           BNB  2026-03-20
5          USDC  2026-03-20
6        Solana  2026-03-20
7          TRON  2026-03-20
8  Figure Heloc  2026-03-20
9      Dogecoin  2026-03-20

# **CRYTO_PRICES**

In [55]:
pd.read_sql('''select * from crypto_prices''',conn)

     coin_id        date     price_usd
0    bitcoin  2025-03-21  84270.843590
1    bitcoin  2025-03-22  84009.532918
2    bitcoin  2025-03-23  83793.308542
3    bitcoin  2025-03-24  85787.709149
4    bitcoin  2025-03-25  87327.729697
..       ...         ...           ...
361  bitcoin  2026-03-17  74858.148701
362  bitcoin  2026-03-18  73926.278992
363  bitcoin  2026-03-19  71255.863503
364  bitcoin  2026-03-20  69871.451480
365  bitcoin  2026-03-20  70307.229205

[366 rows x 3 columns]

**1.Find the highest daily price of Bitcoin in the last 365 days.**

In [56]:
cp1=pd.read_sql('''select * from crypto_prices where coin_id='bitcoin' order by price_usd desc limit 1''',conn)
cp1

   coin_id        date      price_usd
0  bitcoin  2025-10-07  124773.508231

In [57]:
cp11=pd.read_sql('''select coin_id,date,max(price_usd) from crypto_prices where coin_id='bitcoin' ''',conn)
cp11

   coin_id        date  max(price_usd)
0  bitcoin  2025-10-07   124773.508231

**2.Calculate the average daily price of Ethereum in the past 1 year.**

In [58]:
cp2=pd.read_sql('''select coin_id,avg(price_usd) from crypto_prices where coin_id='ethereum' ''',conn )
cp2

  coin_id avg(price_usd)
0    None           None

**3. Show the daily price trend of Bitcoin in January 2025. (or change the month and year according you your data)**

In [59]:
cp3=pd.read_sql('''select * from crypto_prices where coin_id='bitcoin' and date between '2026-01-01' and '2026-01-31' ''',conn)
cp3

    coin_id        date     price_usd
0   bitcoin  2026-01-01  87520.180487
1   bitcoin  2026-01-02  88727.670042
2   bitcoin  2026-01-03  89926.279250
3   bitcoin  2026-01-04  90593.854432
4   bitcoin  2026-01-05  91373.215881
5   bitcoin  2026-01-06  93926.795649
6   bitcoin  2026-01-07  93666.863873
7   bitcoin  2026-01-08  91257.155440
8   bitcoin  2026-01-09  90983.515781
9   bitcoin  2026-01-10  90504.895603
10  bitcoin  2026-01-11  90442.019078
11  bitcoin  2026-01-12  90819.365989
12  bitcoin  2026-01-13  91134.969180
13  bitcoin  2026-01-14  95260.442297
14  bitcoin  2026-01-15  97007.780789
15  bitcoin  2026-01-16  95584.827979
16  bitcoin  2026-01-17  95516.077720
17  bitcoin  2026-01-18  95099.531926
18  bitcoin  2026-01-19  93752.705772
19  bitcoin  2026-01-20  92558.463344
20  bitcoin  2026-01-21  88312.840533
21  bitcoin  2026-01-22  89354.343775
22  bitcoin  2026-01-23  89443.397441
23  bitcoin  2026-01-24  89412.398500
24  bitcoin  2026-01-25  89170.873645
25  bitcoin  2026-01-26  86548.322135
26  bitcoin  2026-01-27  88307.861207
27  bitcoin  2026-01-28  89204.222396
28  bitcoin  2026-01-29  89162.097016
29  bitcoin  2026-01-30  84570.409061
30  bitcoin  2026-01-31  84141.778570

**4. Find the coin with the highest average price over 1 year**

In [60]:
cp4=pd.read_sql('''select coin_id,avg(price_usd) from crypto_prices group by coin_id order by avg(price_usd) desc limit 1''',conn)
cp4

   coin_id  avg(price_usd)
0  bitcoin    97932.286686

**5.Get the % change in Bitcoin’s price between Feb 2025 and Feb 2026**

In [90]:
cp5 = pd.read_sql ("""SELECT(SELECT price_usd FROM crypto_prices WHERE coin_id = 'bitcoin' AND date = '2025-02-01') /
(SELECT price_usd FROM crypto_prices WHERE coin_id = 'bitcoin' AND date = '2026-02-28') * 100 AS percent_change;""", conn)
cp5

  percent_change
0           None

**1.Find the highest oil price in the last 5 years.**

In [62]:
op1=pd.read_sql('''select max(price) as highest_oil_price from oilprice where date >=date('now','-5 years')''',conn)
op1

   highest_oil_price
0             123.64

**2.Get the average oil price per year.**

In [63]:
op2=pd.read_sql('''select strftime('%Y', date) AS year,avg(price) as avg_oil_price from oilprice group by year order by year''',conn)
op2

   year  avg_oil_price
0  2020      39.160437
1  2021      68.135100
2  2022      94.902869
3  2023      77.576532
4  2024      76.632240
5  2025      65.388105
6  2026      60.037000

**3. Show oil prices during COVID crash (March–April 2020).**

In [64]:
op3=pd.read_sql('''select strftime('%Y-%m',date) as month,avg(price) from oilprice group by month having month between '2020-03' and '2020-04' ''',conn)
op3

     month  avg(price)
0  2020-03   29.207727
1  2020-04   16.547619

In [65]:
op31=pd.read_sql('''select * from oilprice where date between '2020-03-01' and '2020-04-30' ''', conn)
op31

          date  price
0   2020-03-02  46.78
1   2020-03-03  47.27
2   2020-03-04  46.78
3   2020-03-05  45.90
4   2020-03-06  41.14
5   2020-03-09  31.05
6   2020-03-10  34.47
7   2020-03-11  33.13
8   2020-03-12  31.56
9   2020-03-13  31.72
10  2020-03-16  28.96
11  2020-03-17  26.96
12  2020-03-18  20.48
13  2020-03-19  25.09
14  2020-03-20  19.48
15  2020-03-23  23.33
16  2020-03-24  21.03
17  2020-03-25  20.75
18  2020-03-26  16.60
19  2020-03-27  15.48
20  2020-03-30  14.10
21  2020-03-31  20.51
22  2020-04-01  20.28
23  2020-04-02  25.18
24  2020-04-03  28.36
25  2020-04-06  26.21
26  2020-04-07  23.54
27  2020-04-08  24.97
28  2020-04-09  22.90
29  2020-04-13  22.36
30  2020-04-14  20.15
31  2020-04-15  19.96
32  2020-04-16  19.82
33  2020-04-17  18.31
34  2020-04-20 -36.98
35  2020-04-21   8.91
36  2020-04-22  13.64
37  2020-04-23  15.06
38  2020-04-24  15.99
39  2020-04-27  12.17
40  2020-04-28  12.40
41  2020-04-29  15.04
42  2020-04-30  19.23

**4.Show oil prices during COVID crash (March–April 2020).**

In [66]:
op4=pd.read_sql('''select min(price) as lowest_oil_price from oilprice where date >=date('now','-10 years')''',conn)
op4

   lowest_oil_price
0            -36.98

**5.Calculate the volatility of oil prices (max-min difference per year).**

In [67]:
op5=pd.read_sql('''select strftime('%Y', date) AS year,max(price)-min(price) as volatility from oilprice group by year order by year''',conn)
op5

   year  volatility
0  2020      100.25
1  2021       38.17
2  2022       52.59
3  2023       27.06
4  2024       20.96
5  2025       25.29
6  2026        8.76

# **Stock Prices**

**1.Get all stock prices for a given ticker**

In [68]:
sp1=pd.read_sql('''select * from stock_prices where ticker='^GSPC' ''',conn)
sp1

,date,open,high,low,close,volume,ticker
0,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3459930000,^GSPC
1,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3484700000,^GSPC
2,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3702460000,^GSPC
3,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3435910000,^GSPC
4,2020-01-08,3238.590088,3267.070068,3236.669922,3253.050049,3726840000,^GSPC
...,...,...,...,...,...,...,...
1509,2026-01-05,6892.189941,6920.379883,6891.560059,6902.049805,5771930000,^GSPC
1510,2026-01-06,6908.029785,6948.689941,6904.020020,6944.819824,5509680000,^GSPC
1511,2026-01-07,6945.069824,6965.689941,6919.189941,6920.930176,5214480000,^GSPC
1512,2026-01-08,6914.109863,6931.279785,6899.330078,6921.459961,5333200000,^GSPC
1513,2026-01-09,6927.830078,6978.359863,6917.640137,6966.279785,5163900000,^GSPC

**2. Find the highest closing price for NASDAQ (^IXIC)**

In [69]:
sp2=pd.read_sql('''select max(close) from stock_prices where ticker='^IXIC' ''',conn)
sp2

     max(close)
0  23958.470703

**3.List top 5 days with highest price difference (high - low) for S&P 500 (^GSPC)**

In [70]:
sp3=pd.read_sql(''' select date,high-low as high_price_difference from stock_prices where ticker='^GSPC' order by high_price_difference desc limit 5''',conn)
sp3

         date  high_price_difference
0  2025-04-09             532.909668
1  2025-04-07             411.529785
2  2025-04-08             357.050293
3  2025-04-10             237.879883
4  2025-11-20             236.300293

**4. Get monthly average closing price for each ticker**

In [71]:
sp4=pd.read_sql('''select strftime('%Y-%m',date) as month,avg(close),ticker from stock_prices group by ticker,month''',conn)
sp4

       month    avg(close) ticker
0    2020-01   3278.202858  ^GSPC
1    2020-02   3277.314183  ^GSPC
2    2020-03   2652.393632  ^GSPC
3    2020-04   2761.975226  ^GSPC
4    2020-05   2919.608484  ^GSPC
..       ...           ...    ...
214  2025-09  24942.674982  ^NSEI
215  2025-10  25494.083519  ^NSEI
216  2025-11  25894.834396  ^NSEI
217  2025-12  25997.738725  ^NSEI
218  2026-01  26086.428850  ^NSEI

[219 rows x 3 columns]

**5. Get average trading volume of NSEI in 2024**

In [72]:
sp5=pd.read_sql('''select avg(volume) as avg_voloume_2024,ticker from stock_prices where ticker='^NSEI' and strftime('%Y',date)='2024' ''',conn)
sp5

   avg_voloume_2024 ticker
0     313560.162602  ^NSEI

# **JOIN QUERIES**

**1. Compare Bitcoin vs Oil average price in 2025.**

In [73]:
jq1=pd.read_sql('''select avg(c.price_usd) as avg_bitcoin_price,avg(o.price) as avg_oil_price from crypto_prices c join oilprice o on c.date = o.date where c.coin_id = 'bitcoin'
and strftime('%Y', c.date) = '2025' ''',conn)
jq1

   avg_bitcoin_price  avg_oil_price
0      103858.668176      63.582923

**2.Check if Bitcoin moves with S&P 500 (correlation idea).**

In [74]:

jq2=pd.read_sql('''select c.date,c.price_usd as bitcoin_price,s.close as stock_closeprice from crypto_prices c join stock_prices s on c.date = s.date where c.coin_id='bitcoin' and s.ticker = '^GSPC' ''',conn)
jq2

           date  bitcoin_price  stock_closeprice
0    2025-03-21   84270.843590       5667.560059
1    2025-03-24   85787.709149       5767.569824
2    2025-03-25   87327.729697       5776.649902
3    2025-03-26   87520.583915       5712.200195
4    2025-03-27   86960.855549       5693.310059
..          ...            ...               ...
198  2026-01-05   91373.215881       6902.049805
199  2026-01-06   93926.795649       6944.819824
200  2026-01-07   93666.863873       6920.930176
201  2026-01-08   91257.155440       6921.459961
202  2026-01-09   90983.515781       6966.279785

[203 rows x 3 columns]

**3. Compare Ethereum and NASDAQ daily prices for 2025.**

In [75]:
jq3=pd.read_sql('''select c.date,c.price_usd as ethereum_price,s.close as NASDAQ_price from crypto_prices c join stock_prices s on c.date = s.date where c.coin_id = 'ethereum' and s.ticker = '^IXIC' and strftime('%Y', c.date) = '2025' ''',conn)
jq3

Empty DataFrame
Columns: [date, ethereum_price, NASDAQ_price]
Index: []

**4. Find days when oil price spiked and compare with Bitcoin price change.**

In [76]:
jq4=pd.read_sql('''select c.price as oilprice,s.price_usd as bitcoin_price from oilprice c join crypto_prices s on c.date=s.date where s.coin_id='bitcoin' order by oilprice desc limit 5''',conn)
jq4

   oilprice  bitcoin_price
0     75.89  104683.424798
1     75.72  104690.650025
2     75.62  106951.272018
3     73.84  105979.229024
4     72.53  105554.493831

**5. Compare top 3 coins daily price trend vs Nifty (^NSEI).**

In [77]:
jq5=pd.read_sql('''select c.date,c.coin_id,c.price_usd,s.close as NSEI_price from crypto_prices c join stock_prices s on c.date=s.date where ticker='^NSEI' order by c.date desc''',conn)
jq5

           date  coin_id     price_usd    NSEI_price
0    2026-01-09  bitcoin  90983.515781  25683.300781
1    2026-01-08  bitcoin  91257.155440  25876.849609
2    2026-01-07  bitcoin  93666.863873  26140.750000
3    2026-01-06  bitcoin  93926.795649  26178.699219
4    2026-01-05  bitcoin  91373.215881  26250.300781
..          ...      ...           ...           ...
195  2025-03-27  bitcoin  86960.855549  23591.949219
196  2025-03-26  bitcoin  87520.583915  23486.849609
197  2025-03-25  bitcoin  87327.729697  23668.650391
198  2025-03-24  bitcoin  85787.709149  23658.349609
199  2025-03-21  bitcoin  84270.843590  23350.400391

[200 rows x 4 columns]

**6. Compare stock prices (^GSPC) with crude oil prices on the same dates**

In [78]:
jq6=pd.read_sql('''select c.date,c.close as stock_price,s.price as oilprice from stock_prices c join oilprice s on c.date=s.date where ticker='^GSPC' ''',conn)
jq6

            date  stock_price  oilprice
0     2020-01-02  3257.850098     61.17
1     2020-01-03  3234.850098     63.00
2     2020-01-06  3246.280029     63.27
3     2020-01-07  3237.179932     62.70
4     2020-01-08  3253.050049     59.65
...          ...          ...       ...
1501  2026-01-05  6902.049805     58.10
1502  2026-01-06  6944.819824     56.97
1503  2026-01-07  6920.930176     56.01
1504  2026-01-08  6921.459961     57.74
1505  2026-01-09  6966.279785     58.96

[1506 rows x 3 columns]

**7. Correlate Bitcoin closing price with crude oil closing price (same date)**

In [79]:
jq7=pd.read_sql('''select c.date,c.price_usd as bitcoin_price,s.price as oilprice from crypto_prices c join oilprice s on c.date=s.date where coin_id='bitcoin' ''',conn)
jq7

           date  bitcoin_price  oilprice
0    2025-03-21   84270.843590     68.52
1    2025-03-24   85787.709149     69.46
2    2025-03-25   87327.729697     69.48
3    2025-03-26   87520.583915     70.05
4    2025-03-27   86960.855549     70.30
..          ...            ...       ...
210  2026-01-26   86548.322135     60.46
211  2026-01-27   88307.861207     62.04
212  2026-01-28   89204.222396     62.75
213  2026-01-29   89162.097016     64.77
214  2026-01-30   84570.409061     64.50

[215 rows x 3 columns]

**8. Compare NASDAQ (^IXIC) with Ethereum price trends**

In [80]:
jq8=pd.read_sql('''select c.close,s.price_usd from stock_prices c join crypto_prices s on c.date = s.date where ticker='^IXIC' and coin_id='ethereum' ''',conn)
jq8

Empty DataFrame
Columns: [close, price_usd]
Index: []

**9. Join top 3 crypto coins with stock indices for 2025**

In [81]:
jq9=pd.read_sql('''select c.date,c.coin_id,s.close,s.ticker from crypto_prices c join stock_prices s on c.date=s.date where strftime('%Y',c.date)='2025' ''',conn)
jq9

           date  coin_id         close ticker
0    2025-03-21  bitcoin   5667.560059  ^GSPC
1    2025-03-21  bitcoin  17784.050781  ^IXIC
2    2025-03-21  bitcoin  23350.400391  ^NSEI
3    2025-03-24  bitcoin   5767.569824  ^GSPC
4    2025-03-24  bitcoin  18188.589844  ^IXIC
..          ...      ...           ...    ...
582  2025-12-30  bitcoin  23419.080078  ^IXIC
583  2025-12-30  bitcoin  25938.849609  ^NSEI
584  2025-12-31  bitcoin   6845.500000  ^GSPC
585  2025-12-31  bitcoin  23241.990234  ^IXIC
586  2025-12-31  bitcoin  26129.599609  ^NSEI

[587 rows x 4 columns]

**10. Multi-join: stock prices, oil prices, and Bitcoin prices for daily comparison**

In [82]:
jq10=pd.read_sql('''select s.date,s.close as stock_price , o.price,c.price_usd as bitcoin_price from stock_prices s join oilprice o on s.date=o.date
join crypto_prices c on s.date=c.date where coin_id='bitcoin' ''',conn)
jq10

           date   stock_price  price  bitcoin_price
0    2025-03-21   5667.560059  68.52   84270.843590
1    2025-03-21  17784.050781  68.52   84270.843590
2    2025-03-21  23350.400391  68.52   84270.843590
3    2025-03-24   5767.569824  69.46   85787.709149
4    2025-03-24  18188.589844  69.46   85787.709149
..          ...           ...    ...            ...
589  2026-01-08  23480.019531  57.74   91257.155440
590  2026-01-08  25876.849609  57.74   91257.155440
591  2026-01-09   6966.279785  58.96   90983.515781
592  2026-01-09  23671.349609  58.96   90983.515781
593  2026-01-09  25683.300781  58.96   90983.515781

[594 rows x 4 columns]

# **STREAMLIT APP STRUCTURE**

In [83]:
!pip install -q streamlit
!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64
import subprocess
subprocess.Popen(["./cloudflared-linux-amd64", "tunnel", "--url", "http://localhost:8501"])
!nohup /content/cloudflared-linux-amd64 tunnel --url http://localhost:8501 &

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 65.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 95.5 MB/s eta 0:00:00
--2026-03-20 13:10:41--  https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
Resolving github.com (github.com)... 140.82.116.3
Connecting to github.com (github.com)|140.82.116.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/cloudflare/cloudflared/releases/download/2026.3.0/cloudflared-linux-amd64 [following]
--2026-03-20 13:10:41--  https://github.com/cloudflare/cloudflared/releases/download/2026.3.0/cloudflared-linux-amd64
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/106867604/731ab2f8-6b77-4adb-a7b3-1104525e9d72?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-20T13%3A42%3A58Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-20T12%3A42%3A06Z&ske=2026-03-20T13%3A42%3A58Z&sks=b&skv=2018-11-09&sig=Z6p1KKqyGlmv2XlLD0HPna5TAzwJVygrZTMqq2zlwAA%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3NDAxMzk5NSwibmJmIjoxNzc0MDEyMTk1LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.XG9HwxyzTbU6b-sE1gvCip0nuIziLeEwMi_d12nuDQk&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream [following]
--2026-03-20 13:10:41--  https://release-assets.githubusercontent.com/github-production-release-asset/106867604/731ab2f8-6b77-4adb-a7b3-1104525e9d72?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-20T13%3A42%3A58Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-20T12%3A42%3A06Z&ske=2026-03-20T13%3A42%3A58Z&sks=b&skv=2018-11-09&sig=Z6p1KKqyGlmv2XlLD0HPna5TAzwJVygrZTMqq2zlwAA%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3NDAxMzk5NSwibmJmIjoxNzc0MDEyMTk1LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.XG9HwxyzTbU6b-sE1gvCip0nuIziLeEwMi_d12nuDQk&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 39667364 (38M) [application/octet-stream]
Saving to: ‘cloudflared-linux-amd64’

cloudflared-linux-a 100%[===================>]  37.83M   252MB/s    in 0.2s

2026-03-20 13:10:41 (252 MB/s) - ‘cloudflared-linux-amd64’ saved [39667364/39667364]

nohup: appending output to 'nohup.out'

In [84]:
!pip install streamlit-option-menu

Collecting streamlit-option-menu
  Downloading streamlit_option_menu-0.4.0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: streamlit>=1.36 in /usr/local/lib/python3.12/dist-packages (from streamlit-option-menu) (1.55.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (8.3.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (3.1.46)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (26.0)
Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (0.9.1)
Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (0.10.2)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (6.5.1)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (2.18.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.36->streamlit-option-menu) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (2026.2.25)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.36->streamlit-option-menu) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (0.30.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (1.17.0)
Downloading streamlit_option_menu-0.4.0-py3-none-any.whl (829 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 829.3/829.3 kB 16.3 MB/s eta 0:00:00
Installing collected packages: streamlit-option-menu
Successfully installed streamlit-option-menu-0.4.0

In [96]:
%%writefile app.py
import streamlit as st
import pandas as pd
import sqlite3
from streamlit_option_menu import option_menu

# Database connection
conn = sqlite3.connect("cmarket.db")

st.title("🪙🛢️📈 Cross-Market Analysis")

with st.sidebar:
    selected = option_menu(
        "Main Menu",
        ["Filters and Data Exploration", "SQL Query runner", "Top 3 Crypto Analysis"],
        icons=['filter', 'search', 'map'],
        menu_icon="cast",
        default_index=0
    )
if selected == "Filters and Data Exploration":

    st.header("Average Price",divider=True)
    st.markdown(''':orange[Select the date range]''')

    import streamlit as st
    col1,col2=st.columns(2)
    with col1:
      start_date = st.date_input("Start Date",width=150,key="start_date",value="2025-01-01")
    with col2:
      end_date = st.date_input("End Date",width=150,key="end_date")

    if start_date and end_date:
      col1, col2=st.columns(2)
      col3,col4 = st.columns(2)
      cp=pd.read_sql(f'''select avg(price_usd) as bitcoin_avg from crypto_prices where coin_id='bitcoin' and date between "{start_date}" and "{end_date}" ''',conn )
      bitcoin=cp['bitcoin_avg'][0]
      op=pd.read_sql(f'''select avg(price) as oil_avg from oilprice where date between "{start_date}" and "{end_date}" ''',conn)
      oil=op['oil_avg'][0]
      sp=pd.read_sql(f'''select avg(close) as sp500 from stock_prices where ticker='^GSPC'and date between "{start_date}" and "{end_date}" ''',conn)
      sp500=sp['sp500'][0]
      nty=pd.read_sql(f'''select avg(close) as Nifty from stock_prices where ticker='^NSEI'and date between "{start_date}" and "{end_date}" ''',conn)
      Nifty=nty['Nifty'][0]
      col1.metric("Average Bitcoin price",round(bitcoin,2) ,border=True,width=1550)
      col2.metric("Average Oil Price",round(oil,2),border=True,width=510)
      col3.metric("Average S&P 500",round(sp500,2),border=True,width=715)
      col4.metric("Average Nifty",round(Nifty,2),border=True,width=715)
    df=pd.read_sql(f'''select c.date,
        c.price_usd as bitcoin_price,o.price AS oil_price,
        s.close as sp500_close
        from crypto_prices c
        join oilprice o on c.date = o.date
        join stock_prices s
        on c.date = s.date
        and s.ticker = '^GSPC'
        where c.coin_id = 'bitcoin'
        and c.date=date('now') or c.date between "{start_date}" and "{end_date}" ''',conn)
    st.subheader("Market Data",divider=True)
    st.dataframe(df)

if selected == "Top 3 Crypto Analysis":
  crypto=st.selectbox("Select a Cryptocurrency",("bitcoin","ethereum"))
  col1,col2=st.columns(2)
  with col1:
      start_date = st.date_input("Start Date",width=150,value="2025-01-01")
  with col2:
      end_date = st.date_input("End Date",width=150)
  df = pd.read_sql(f'''select date,price_usd from crypto_prices where coin_id="{crypto}" and date between "{start_date}" and "{end_date}" ''', conn)
  st.subheader("Filtered Market Data",divider=True)
  st.dataframe(df)
  lc=pd.read_sql(f'''select date,price_usd from crypto_prices where coin_id="{crypto}" and date between "{start_date}" and "{end_date}" order by date''',conn)
  st.subheader(f"{crypto} Price Trend",divider=True)
  st.line_chart(df.set_index("date"))

# ---------------------------------------------------
# QUERIES PAGE
# ---------------------------------------------------
if selected == "SQL Query runner":

    st.header("SQL Query runner")

    option = st.selectbox(
        "Select a Query",
        (
            # Cryptocurrencies
            "Top 3 Cryptocurrencies by Market Cap",
            "Coins With Circulating Supply > 90%",
            "Coins Within 10% of ATH",
            "Average Market Cap Rank (Volume > 1B)",
            "Most Recently Updated Coin",

            # Crypto Prices
            "Highest Bitcoin Price",
            "Average Ethereum Price",
            "Bitcoin January Trend",
            "Coin with highest Average Price",
            "Percentage change in bitcoin price",

            # Oil Queries
            "Highest Oil Price",
            "Average Oil Price Per Year",
            "Covid Crash Price",
            "Lowest Oil Price",
            "Volatality of oilprice",

            # Stock Queries
            "Highest S&P 500 Close",
            "Top 5 Highest Price Difference Days",
            "Monthly Average Close (All Stocks)",
            "Average trading volume in NSEI",


            # Join Queries
            "Bitcoin vs Oil Comparison",
            "Bitcoin vs S&P 500",
            "Ethereum vs NASDAQ",
            "Compare oilprice with bitcoin price",
            "top 3 coins daily price trend vs Nifty",
            "Compare stock prices (^GSPC) with crude oil prices",
            "Correlate Bitcoin closing price with crude oil",
            "Compare NASDAQ (^IXIC) with Ethereum price trends",
            "top 3 crypto coins with stock indices"
        )
    )
 # -------------------------------
    # CRYPTOCURRENCIES
    # -------------------------------

    if option == "Top 3 Cryptocurrencies by Market Cap":
        df = pd.read_sql('''select * from crypto_prices where coin_id='bitcoin' order by price_usd desc limit 1''',conn)
        st.subheader("Top 3 Cryptocurrencies by Market Cap")
        st.dataframe(df)

    if option == "Coins With Circulating Supply > 90%":
        df = pd.read_sql('''select id,name,circulating_supply,total_supply from crypto_currencies where circulating_supply > 0.90 * total_supply''',conn)
        st.subheader("Coins With Circulating Supply > 90%")
        st.dataframe(df)
    if option =="Coins Within 10% of ATH":
      df=pd.read_sql('''select * from crypto_currencies where current_price >= 0.9 * ath''', conn)
      st.subheader("Coins Within 10% of ATH")
      st.dataframe(df)
    if option =="Average Market Cap Rank (Volume > 1B)":
      df=pd.read_sql(''' select name,avg(market_cap_rank) from crypto_currencies where total_volume>1000000000''', conn)
      st.subheader("Average Market Cap Rank (Volume > 1B)")
      st.dataframe(df)
    if option=="Most Recently Updated Coin":
      df=pd.read_sql('''select name,date from crypto_currencies order by date desc limit 10''',conn)
      st.subheader("Most Recently Updated Coin")
      st.dataframe(df)
    if option=="Highest Bitcoin Price":
      df=pd.read_sql('''select * from crypto_prices where coin_id='bitcoin' order by price_usd desc limit 1''',conn)
      st.subheader("Highest Bitcoin Price")
      st.dataframe(df)
    if option =="Average Ethereum Price":
      df=pd.read_sql('''select coin_id,avg(price_usd) from crypto_prices where coin_id='ethereum' ''',conn )
      st.subheader("Average Ethereum Price")
      st.dataframe(df)
    if option =="Bitcoin January Trend":
      df=pd.read_sql('''select * from crypto_prices where coin_id='bitcoin' and date between '2026-01-01' and '2026-01-31' ''',conn)
      st.subheader("Bitcoin January Trend")
      st.dataframe(df)
    if option=="Coin with highest Average Price":
      df=pd.read_sql('''select coin_id,avg(price_usd) from crypto_prices group by coin_id order by avg(price_usd) desc limit 1''',conn)
      st.subheader("Coin with highest Average Price")
      st.dataframe(df)
    if option=="Percentage change in bitcoin price":
      df=pd.read_sql ("""SELECT(SELECT price_usd FROM crypto_prices WHERE coin_id = 'bitcoin' AND date = '2025-09-30') /
(SELECT price_usd FROM crypto_prices WHERE coin_id = 'bitcoin' AND date = '2026-09-30') * 100 AS percent_change;""", conn)
      st.subheader("Percentage change in bitcoin price")
      st.dataframe(df)
    if option=="Highest Oil Price":
      df=pd.read_sql('''select max(price) as highest_oil_price from oilprice where date >=date('now','-5 years')''',conn)
      st.subheader("Highest Oil Price")
      st.dataframe(df)
    if option=="Average Oil Price Per Year":
      df=pd.read_sql('''select strftime('%Y', date) AS year,avg(price) as avg_oil_price from oilprice group by year order by year''',conn)
      st.subheader("Average Oil Price Per Year")
      st.dataframe(df)
    if option == "Covid Crash Price":
      df=pd.read_sql('''select strftime('%Y-%m',date) as month,avg(price) from oilprice group by month having month between '2020-03' and '2020-04' ''',conn)
      st.subheader("Covid Crash Price")
      st.dataframe(df)
    if option =="Lowest Oil Price":
      df=pd.read_sql('''select min(price) as lowest_oil_price from oilprice where date >=date('now','-10 years')''',conn)
      st.subheader("Lowest Oil Price")
      st.dataframe(df)
    if option=="Volatality of oilprice":
      df=pd.read_sql('''select strftime('%Y', date) AS year,max(price)-min(price) as volatility from oilprice group by year order by year''',conn)
      st.subheader("Volatality of oilprice")
      st.dataframe(df)
    if option=="Highest S&P 500 Close":
      df=pd.read_sql('''select * from stock_prices where ticker='^GSPC' ''',conn)
      st.subheader("Highest S&P 500 Close")
      st.dataframe(df)
    if option=="Top 5 Highest Price Difference Days":
      df=pd.read_sql('''select max(close) from stock_prices where ticker='^IXIC' ''',conn)
      st.subheader("Top 5 Highest Price Difference Days")
      st.dataframe(df)
    if option=="Monthly Average Close (All Stocks)":
      df=pd.read_sql(''' select date,high-low as high_price_difference from stock_prices where ticker='^GSPC' order by high_price_difference desc limit 5''',conn)
      st.subheader("Monthly Average Close (All Stocks)")
      st.dataframe(df)
    if option=="Average trading volume in NSEI":
      df=pd.read_sql('''select avg(volume) as avg_voloume_2024,ticker from stock_prices where ticker='^NSEI' and strftime('%Y',date)='2024' ''',conn)
      st.subheader("Average trading volume in NSEI")
      st.dataframe(df)
    if option=="Bitcoin vs Oil Comparison":
      df=pd.read_sql('''select c.date,c.price_usd as bitcoin_price,s.close as stock_closeprice from crypto_prices c join stock_prices s on c.date = s.date where c.coin_id='bitcoin' and s.ticker = '^GSPC' ''',conn)
      st.subheader("Bitcoin vs Oil Comparison")
      st.dataframe(df)
    if option=="Bitcoin vs S&P 500":
      df=pd.read_sql('''select c.date,c.price_usd as bitcoin_price,s.close as stock_closeprice from crypto_prices c join stock_prices s on c.date = s.date where c.coin_id='bitcoin' and s.ticker = '^GSPC' ''',conn)
      st.subheader("Bitcoin vs S&P 500")
      st.dataframe(df)
    if option=="Ethereum vs NASDAQ":
      df=pd.read_sql('''select c.date,c.price_usd as ethereum_price,s.close as NASDAQ_price from crypto_prices c join stock_prices s on c.date = s.date where c.coin_id = 'ethereum' and s.ticker = '^IXIC' and strftime('%Y', c.date) = '2025' ''',conn)
      st.subheader("Ethereum vs NASDAQ")
      st.dataframe(df)
    if option=="Compare oilprice with bitcoin price":
      df=pd.read_sql('''select c.price as oilprice,s.price_usd as bitcoin_price from oilprice c join crypto_prices s on c.date=s.date where s.coin_id='bitcoin' order by oilprice desc limit 5''',conn)
      st.subheader("Compare oilprice with bitcoin price")
      st.dataframe(df)
    if option=="top 3 coins daily price trend vs Nifty":
      df=pd.read_sql('''select c.date,c.coin_id,c.price_usd,s.close as NSEI_price from crypto_prices c join stock_prices s on c.date=s.date where ticker='^NSEI' order by c.date desc''',conn)
      st.subheader("top 3 coins daily price trend vs Nifty")
      st.dataframe(df)
    if option=="Compare stock prices (^GSPC) with crude oil prices":
      df=pd.read_sql('''select c.date,c.close as stock_price,s.price as oilprice from stock_prices c join oilprice s on c.date=s.date where ticker='^GSPC' ''',conn)
      st.subheader("Compare stock prices (^GSPC) with crude oil prices")
      st.dataframe(df)
    if option=="Correlate Bitcoin closing price with crude oil":
      df=pd.read_sql('''select c.date,c.price_usd as bitcoin_price,s.price as oilprice from crypto_prices c join oilprice s on c.date=s.date where coin_id='bitcoin' ''',conn)
      st.subheader("Correlate Bitcoin closing price with crude oil")
      st.dataframe(df)
    if option=="Compare NASDAQ (^IXIC) with Ethereum price trends":
      df=pd.read_sql('''select c.close,s.price_usd from stock_prices c join crypto_prices s on c.date = s.date where ticker='^IXIC' and coin_id='ethereum' ''',conn)
      st.subheader("Compare NASDAQ (^IXIC) with Ethereum price trends")
      st.dataframe(df)
    if option=="top 3 crypto coins with stock indices":
      df=pd.read_sql('''select c.date,c.coin_id,s.close,s.ticker from crypto_prices c join stock_prices s on c.date=s.date where strftime('%Y',c.date)='2025' ''',conn)
      st.subheader("top 3 crypto coins with stock indices")
      st.dataframe(df)

Overwriting app.py

In [91]:
!streamlit run /content/app.py &>/content/logs.txt &  # here instead of app.py please rename with your file name

In [92]:
!grep -o 'https://.*\.trycloudflare.com' nohup.out | head -n 1 | xargs -I {} echo "Your tunnel url {}"

Your tunnel url https://vintage-appeals-glen-communication.trycloudflare.com